# Language: Slovak
# File ending: SK
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

# Welcome Message
WELCOME_DEF="Vitajte v inçtalaŸnom programe syst‚mu" /fLightGreen %1 /fCyan %2 /fGray "."
WELCOME_ADV="Vitajte v" /fLightRed "pokroŸilej" /fGray "inçtal cii syst‚mu" /fLightGreen %1 /fCyan %2 /fGray /s- .
WELCOME_0=/p
WELCOME_1=/fLightGreen "%1" /fGray "je kompletnì operaŸnì syst‚m. Ak sa ho rozhodnete nainçtalovaœ" /p "na svoj poŸ¡taŸ, m“§ete" /fLightRed /BlinkOn "prep¡saœ" /BlinkOff /fGray "s£Ÿasnì operaŸnì syst‚m" /p "(napr¡klad Windows.)" /fGray
WELCOME_2=/fGray /c32 "Ak to nie je v ç z mer, pros¡m" /fLightRed "zastavte TERAZ!" /fGray
WELCOME_3=
WELCOME_4=
WELCOME_5=/fGray /p

HRULE=/fDarkGray /x 0xC4 /fGray

CONTINUE=/p "Chcete pokraŸovaœ" /c32
REBOOT=/p "Chcete teraz reçtartovaœ" /c32

AUTO_YES="[A,N]?" /fWhite "A" /fGray
AUTO_NO="[A,N]?" /fWhite "N" /fGray
AUTO_FMT=/s- "[U,R,N]?" /fWhite "R" /fGray

PROMPT_YESNO=/s AN
PROMPT_FMT=/s URN

ABORTED=/fLightRed "Inçtal cia syst‚mu" %1 %2 "bola preruçen ." /e /fGray /bBlack

PARTITION_AUTO="Automaticky rozdeliœ disk" /fWhite %1 /s- /fGray .
PARTITION_WARN=/fYellow "UPOZORNENIE:" /fGray "Pre KERNL86 je vy§adovanì oddiel FAT16 menç¡ ako 2 GB."
PARTITION_MBR="Aktualizovaœ Master Boot Record na disku" /fWhite %1 /s- /fGray .
PARTITION_ACTIVE="Nastaviœ oddiel disku" /fWhite %1 /fGray "ako akt¡vny."
PARTITION_DONE=/p "Pre aktiv ciu nov‚ho rozdelenia disku mus¡te reçtartovaœ poŸ¡taŸ."

FORMAT="Disk" /fWhite %1 /fGray "sa nezd  byœ naform tovanì."
FORMAT_DEF="Chcete disk naform tovaœ" /c32
FORMAT_ADV="Ako chcete disk naform tovaœ" /s- /c32 ( /fWhite "U" /fGray "pln‚," /c32 /fWhite "R" /fGray "ìchle," /c32 /fWhite "N" /fGray "ie)" /c32

FILESYSTEM_TEST="Testovanie s£borov‚ho syst‚mu na disku" /fWhite %1 /s- /fGray .
INSERT_DISKETTE="Vlo§te disketu" /fWhite #%1 /fGray (%2) "do" /fWhite %3 /fGray "."
PRESS_KEY="PokraŸujte stlaŸen¡m kl vesu."

TARGET_ASK="Kam si §el te nainçtalovaœ" /fLightGreen %1 /s- /fGray "?" /c32
TARGET_PROMPT=/fWhite /bBlue %1
TARGET_BAD=/fLightRed "Po§adovanì neplatnì disk. Nemo§no inçtalovaœ na disketu."

CHANGE_PATH="Cesta" /fWhite %1 /fGray "u§ existuje." /p "¦el te si zmeniœ inçtalaŸnì adres r" /c32

BACKUP_OLD="Na disku" /fWhite %1 /fGray "bol n jdenì predch dzaj£ci operaŸnì syst‚m." /s+ /p "Chcete pred inçtal ciou z lohovaœ star‚ s£bory" /c32
BACKUP_ASK="Kam si §el te umiestniœ z lo§n‚ s£bory?" /c32
BACKUP_PROMPT=/fWhite /bBlue %1
BACKUP_BAD=/fLightRed "Po§adovanì neplatnì cie–. Z lohu na toto miesto nemo§no vykonaœ." /fGray

DELETE_OLD="Existuj£ce s£bory v" /fWhite %1 /fGray "m“§u byœ jednoducho prep¡san‚." /p "Chcete pred inçtal ciou kompletne vymazaœ starì adres r" /c32

FORCE_MBR="Vyn£tiœ aktualiz ciu Master Boot Record na disku" /fWhite %1 /fGray /c32
SYS_FILES="Inçtalovaœ nov‚ s£bory zav dzania syst‚mu na disk" /fWhite %1 /fGray /c32
CFG_FILES="Nahradiœ konfiguraŸn‚ s£bory syst‚mu na disku" /fWhite %1 /fGray /c32

STATUS_MSG="Nastavenia inçtal cie:" /p
STATUS_CPU=/r4/c32 "Platforma (CPU)" /fWhite %1 /fGray (%2)
STATUS_FROM=/r4/c32 "Inçtalovaœ z" /fWhite %1 /fGray
STATUS_DRV=/r4/c32 "Cie–ovì disk" /fWhite %1 /fGray (disk %2, oddiel %3)
STATUS_DOS=/r4/c32 "InçtalaŸn  cesta DOS" /fWhite %1 /fGray
STATUS_BAK=/r4/c32 "Z lohovaœ predch. OS" /fWhite %1 /fGray
STATUS_POS=/r4/c32 "Adres r predch. OS" /fWhite %1 /fGray
STATUS_MBR=/r4/c32 "Inçtalovaœ novì MBR" /fWhite %1 /fGray
STATUS_SYS=/r4/c32 "Kop¡rovaœ syst‚m. s£bory" /fWhite %1 /fGray
STATUS_CFG=/r4/c32 "Kop¡rovaœ konfig. s£bory" /fWhite %1 /fGray

INSTALL_NOW="Teraz sme pripraven¡ na inçtal ciu syst‚mu" /fLightGreen %1 /fCyan %2 /fGray /s- .
EXTRACTION="Rozba–ovanie s£borov syst‚mu" /fLightGreen %1 /fCyan %2 /fGray /s- .
UPDATE_LST="Aktualiz cia zoznamu bal¡kov." /p

DO_BACKUP="Vytv ranie z lohy s£borov predch dzaj£ceho OS do" /fWhite %1 /fGray /s- .
DO_ERASE="Mazanie star‚ho adres ra" /fWhite %1 /fGray " a s£borov."
DO_SYSFILES="Prenos novìch syst‚movìch s£borov na disk" /fWhite %1 /fGray /s- .
DO_FORCEMBR="Vyn£ten  aktualiz cia MBR na disku" /fWhite %1 /fGray /s- .
DO_ACTIVATE="Nastavenie akt¡vneho zav dzacieho oddielu na disku" /fWhite %1 /fGray "na oddiel" /fWhite %2 /s- /fGray .
DO_CFGFILES="Prenos novìch konfiguraŸnìch s£borov na disk" /fWhite %1 /fGray /s- .
DO_PREPARE="Pr¡prava na inçtal ciu spustite–nìch s£borov a n strojov."
DO_INSTALL="Inçtal cia s£borov" /fLightGreen %1 /fGray "pre" /fWhite %2 /fGray /s- .

DONE_NOW="Inçtal cia syst‚mu" /fLightGreen %1 /fCyan %2 /fGray "bola dokonŸen ."
REBOOT_NOW="Chcete teraz reçtartovaœ" /c32

REMOVE_MEDIA="Mali by ste vybraœ vçetky diskety a CD m‚di ."

SUCCESS=/fLightGreen "éspech." /fGray
FAILED=/fLightRed "Zlyhalo." /fGray

# Copyright and License Notices
TITLE=/fLightGreen %1 /fLightCyan %2 /s- /fWhite + /fGray " Inçtal tor (" /fWhite FDI-x86 /fGray ")"
COPYRIGHT=/fDarkGray "Vydan‚ pod licenciou GPL v2.0."/p "Copyright" 2021-2022 "Jerome Shidel." /fGray /p
TRADEMARK="FreeDOS je ochrann  zn mka Jima Halla," 2001-2022

# Help screen
HELP_0="pou§itie: SETUP.BAT [vo–by] [cie–]"
HELP_1=""
HELP_2="  [bez volieb]    vykonaœ inçtal ciu s predvolenìmi hodnotami"
HELP_3=
HELP_4="  adv             spustiœ inçtal ciu v pokroŸilom re§ime (viac ot zok)"
HELP_5=
HELP_6="  auto            vykonaœ plne automatick£ inçtal ciu bez ot zok." /p/r18/c32 "neodpor£Ÿa sa a malo by sa pou§iœ iba na hardv‚ri" /p/r18/c32 "bez predch dzaj£ceho operaŸn‚ho syst‚mu."
HELP_7=
HELP_8="  [cie–]          prednastaviœ disk a/alebo cestu pre cie–ov£ inçtal ciu"
HELP_9=
HELP_10="  info            zobraziœ nastavenia inçtal tora a ukonŸiœ"
HELP_11=
HELP_12="  mbr             vyn£tiœ aktualiz ciu MBR a ukonŸiœ"
HELP_13=
HELP_14=/n
HELP_15=/n

# Error Messages
ERROR_CRITICAL=/fLightRed "KRITICKµ chyba:" /fGray /c32
ERROR_NoHDD="Nemo§no n jsœ rozdelenì a naform tovanì pevnì disk."
ERROR_MINOR=/fLightRed "chyba:" /fGray /c32
ERROR_Option="Nezn ma alebo neplatn  vo–ba pr¡kazov‚ho riadka" /s- "`" /fWhite %1 /fGray "'."
ERROR_NoCfgEnv="Nemo§no urŸiœ z kladn£ konfigur ciu syst‚mu a nastavenia ciest."
ERROR_NotFreeCOM="Tento d vkovì s£bor vy§aduje FreeCOM alebo kompatibilnì shell pre FreeDOS."
ERROR_MissingFreeCOM="Nemo§no n jsœ pr¡kazovì shell FreeDOSu FreeCOM."
ERROR_MissingAUTOEXEC="Nemo§no n jsœ sp£çœac¡ d vkovì s£bor FreeDOSu FDAUTO.BAT."
ERROR_MakeDir="Nemo§no vytvoriœ adres r" /fWhite %1 /fGray /s- .
ERROR_BackupCfg="Nemo§no z lohovaœ zav dzacie a/alebo konfiguraŸn‚ s£bory."
ERROR_BackupOS="Nemo§no z lohovaœ s£bory v cie–ovom adres ri."
ERROR_Partition="Doçlo k chybe pri rozde–ovan¡ disku. Pevnì disk nemus¡ byœ pr¡tomnì" /p "alebo m“§e byœ pre s£Ÿasnì operaŸnì syst‚m nevidite–nì." /p /p "Je vy§adovan  in  met¢da rozdelenia disku."
ERROR_NoPartition="Nemo§no n jsœ BIOS oddiel pre" /fWhite %1 /fGray /s- . /s+ /p "Odpor£Ÿa sa ruŸn  inçtal cia (alebo pokroŸilì re§im bez vyn£ten‚ho MBR)."
ERROR_Format="Pri pokuse o form tovanie disku" /fWhite %1 /fGray /s- " doçlo k chybe." /s+ /p /p "Na form tovanie bude vy§adovanì inì postup."
ERROR_FileSystem="Nemo§no inicializovaœ doŸasnì priestor na disku" /fWhite %1 /s- /fGray .
ERROR_CfgBackup="Nemo§no konfigurovaœ z lo§nì adres r."
ERROR_MBRBackup="Nemo§no vytvoriœ z lohu Master Boot Record pre disk" /fWhite %1 /fGray /s- .
ERROR_SysFiles="Nemo§no skop¡rovaœ syst‚mov‚ s£bory na disk" /fWhite %1 /fGray /s- .
ERROR_BootSector="Nemo§no aktualizovaœ boot sektor disku" /fWhite %1 /fGray /s- .
ERROR_MBRUpdate="Nemo§no aktualizovaœ MBR disku" /fWhite %1 /fGray /s- .
ERROR_Activate="Nemo§no nastaviœ disk" /fWhite %1 /fGray "na zav dzac¡ oddiel" /fWhite %2 /fGray /s- .
ERROR_CfgFiles="Nemo§no nainçtalovaœ nov‚ konfiguraŸn‚ s£bory na disk" /fWhite %1 /fGray /s- .
ERROR_XfrFiles="Nemo§no duplikovaœ vy§adovanì s£bor inçtal tora do" /fWhite %1 /fGray /s- .
ERROR_SAF="Pri rozba–ovan¡ arch¡vu" /fWhite %1 /fGray " doçlo k probl‚mu."
ERROR_WTF="PoŸas jednoduchej oper cie doçlo k nezn mej a nepravdepodobnej chybe."
