# Language: Slovak (sk)
# File ending: sk
# Codepage: 852
# This translation was created by Google AI
# Please help the FreeDOS group to improve it.

STR1_1 = 'Medzin†rodnÇ rozÁ°renie BIOSu kl†vesnice pre projekt FreeDOS';
STR1_2 = 'PoslednÏ modul je: ';
STR1_3 = 'Rozloßenie kl†vesnice: ';
STR1_4 = 'Rezidentn† üasú Keyb bola odstr†nen†.';
STR1_5 = 'Typ kl†vesnice       : rozÁ°ren† AT';
STR1_6 = 'Typ kl†vesnice       : Átandardn† PC';
STR1_7 = 'Autor kompil†cie     : ';
STR1_8 = 'Info o kompil†cii    : ';
STR1_9 = 'JaponskÇ rozÁ°renia akt°vne';

STR2_1 = 'Bola nainÁtalovan† in† verzia Keyb.';
STR2_2 = 'Bol nainÁtalovanÏ nekompatibilnÏ ovl†daü kl†vesnice.';
STR2_3 = 'ChÏba identifik†tor kl†vesnice';
STR2_4 = 'ZadanÏ s£bor sa nepodarilo otvoriú.';
STR2_5 = 'Rezidentn£ üasú Keyb nebolo moßnÇ odstr†niú.';
STR2_6 = 'Intern† chyba: Glob†lna pamÑú pr°liÁ mal† (kontaktujte autora).';
STR2_7 = 'Keyb vyßaduje (st†le) procesor AT/286 alebo lepÁ°';
STR2_8 = 'KEYB nebol nainÁtalovanÏ';
STR2_9 = 'Preúaßovanie nie je (st†le) podporovanÇ';
STR2_10 = 'Tabuñku kl†vesnice sa nepodarilo vytvoriú';
STR2_11 = 'NeplatnÏ prep°naü -  ';
STR2_12 = 'Codepage nebola v s£bore defin°ci° kl†vesnice n†jden† - ';
STR2_13 = 'NeplatnÏ alebo poÁkodenÏ s£bor';
STR2_14 = 'S£bor neobsahuje inform†cie pre toto rozloßenie/id';
STR2_15 = 'S£bor KL pr°liÁ veñkÏ (maximum (st†le) 3KB)';
{ STR2_16 = 'Chyba pri komunik†cii so zariaden°m CON';
STR2_17 = 'Codepage nebola pripraven†';  }
STR2_18 = 'Bola n†jden† nekompatibiln† verzia DR-DOS KEYB';
STR2_19 = 'Nekompatibiln† verzia deskriptorov kl†vesnice';
STR2_20 = 'NeplatnÏ kontrolnÏ s£üet d†tovÇho bloku';
STR2_21 = 'PoßadovanÇ podmapovanie nezodpoved† aktu†lnej codepage';
STR2_22 = 'PoßadovanÏ s£bor knißnice nie je uzavretÏ na £pravy';
STR2_50 = 'Varovanie: nepodarilo sa uvoñniú predch†dzaj£ci MCB. Chyba DOSu: ';
STR2_51 = 'Kritick† chyba: nepodarilo sa alokovaú pamÑú. Chyba DOSu: ';

STR3_1  = '("Taurus") Druh† gener†cia ovl†daüa kl†vesnice pre FreeDOS';
STR3_2  = 'Licencia: GNU GPL 2.0 alebo novÁia';
STR3_3  = '(/? pomoc, /V podrobne)';
STR3_4  = 'KEYB n†zov[,[CP][,s£bor] [/ID:nnn] [/E] [/9] [/I] [/Dx] [/V] [/L=m]';
STR3_5  = 'n†zov       FyzickÏ identifik†tor rozloßenia, napr. GR alebo SK';
STR3_6  = 'CP          Poüiatoün† codepage pre rozloßenie';
STR3_7  = 's£bor       S£bor obsahuj£ci inform†cie o rozloßen°';
STR3_8 = '/ID:nnn     ¨°selnÏ identifik†tor variantu kl†vesnice';
STR3_9  = '/?          Zobraz° t£to pomoc';
STR3_10 = '/9          InÁtaluje obsluhu int9h (nekompatibilnÇ s /E)';
STR3_11 = '/B          P°pnutie vypnutÇ: vypne zvukovÇ efekty KEYB (reproduktor)';
STR3_12 = '/CAPSLOCK=ON|OFF    Zapne alebo vypne Caps Lock';
STR3_13 = '/Dx         DesatinnÏ oddeñovaü: x je znak, ktorÏ sa m† poußiú';
STR3_14 = '/E          Urüuje, ße kl†vesnica je rozÁ°ren† (Enhanced)';
STR3_15 = '            (nekompatibilnÇ s /9)';
STR3_16 = '/I          (force Install) InÁtaluje keyb bezpodmieneüne';
STR3_17 = '/L=m        (force subLayout) Vyn£ti poußitie podrozloßenia m';
STR3_18 = '/NOHI       Zabr†ni KEYB v naü°tan° d†t do pamÑte High Memory';
STR3_19 = '/NOUMB      Zabr†ni KEYB v naü°tan° d†t do pamÑte Upper Memory';
STR3_20 = '/NUMLOCK=ON|OFF    Zapne alebo vypne Num Lock';
STR3_21 = '/S          (Safemode) zak†ße reúazce... (pozri dokument†ciu)';
STR3_22 = '/SCROLLLOCK=ON|OFF    Zapne alebo vypne Scroll Lock';
STR3_23 = '/U          (Uninstall) uvoñn° ovl†daü z pamÑte';
STR3_24 = '/V          (Verbose) zobraz° podrobnÇ inform†cie o inÁtal†cii';
STR3_25 = '“alÁie inform†cie: README.TXT';

STR4_1  = 'Pr°znak akt°vneho ovl†daüa : ';
STR4_2  = 'Aktu†lny n†zov rozloßenia    : ';
STR4_3  = 'DETAILY AKTUµLNêHO ROZLO¶ENIA:';
STR4_4  = 'Aktu†lna codepage           : ';
STR4_4b = 'Aktu†lne podmapovanie        : ';
STR4_5  = 'Poüet podmapovan°           : ';
STR4_6  = 'Pr°pustnÇ codepages         : ';

STR5_1 = 'CHYBA: vektor int15h bol prep°sanÏ';
STR5_2 = 'CHYBA: vektor int2Fh bol prep°sanÏ';
STR5_3 = 'CHYBA: vektor int16h bol prep°sanÏ';
STR5_4 = 'CHYBA: vektor int9h bol prep°sanÏ';

STR6_1 = 'Caps lock ZAPNUTÌ';
STR6_2 = 'Caps lock VYPNUTÌ';
STR6_3 = 'Scroll lock ZAPNUTÌ';
STR6_4 = 'Scroll lock VYPNUTÌ';
STR6_5 = 'Num lock ZAPNUTÌ';
STR6_6 = 'Num lock VYPNUTÌ';

