# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vline [vo–by]

Vykresl¡ Ÿiaru.

    [§iadne]    Vykresl¡ ako lok lnu jednoduch£ "dumb" Ÿiaru na aktu lnom
                riadku.
    /K n        Pou§iœ n namiesto znaku r mu na detekciu hran¡c.
    single      Vykresl¡ jednu Ÿiaru.
    double      Vykresl¡ dvojit£ Ÿiaru.
    hidden      Vykresl¡ nevidite–n£ "dumb" Ÿiaru.
    dumb        Vykresl¡ "dumb" Ÿiaru bez oh–adu na to, Ÿo u§ existuje.

    tba         (St le vo vìvoji, Ôalçie bud£ ozn men‚)
