
$OS_NAME$ es un sistema operativo de c¢digo libre compatible con DOS que
se puede usar para jugar a juegos cl sicos de DOS, ejecutar arcaicos programas
profesionales o desarrollar sistemas incrustados. Cualquier programa que se
pueda ejecutar en MS-DOS se deber¡a poder ejecutar en $OS_NAME$.
*

En $OS_NAME$ se puede jugar a tus juegos de DOS favoritos. Y hay muchos juegos
cl sicos a los que puede jugar: Wolfenstein 3D, Doom, Commander Keen,
Rise of the Triad, Jill of the Jungle, Duke Nukem ­y muchos otros!
*

¨Necesita extraer datos de alg£n viejo programa burocr tico? ¨O necesita
ejecutar un informe de su antiguo sistema contable? ­Entonces solo tiene
que instalar $OS_NAME$, y todo listo!
*

Muchos sistemas empotrados funcionan con DOS, aunque los sistemas m s
modernos ya funcionan con Linux. Si mantiene un antiguo sistema incrustado es
probable que est‚ ejecutando DOS, y ah¡ $OS_NAME$ encajar¡a perfectamente.
*

$OS_NAME$ es software libre!
Es gratis descargar y usar $OS_NAME$.
*

FreeDOS Alfa 1 sali¢ el 16 de septiembre de 1994.
Desde entonces hemos pasado por m s de 30 a¤os de historia.
*

­Tambi‚n puede compartir y disfrutar $OS_NAME$ con otras personas! Y tambi‚n
puedes ver y modificar nuestro c¢digo fuente, puesto que todos los programas
de $OS_NAME$ est n bajo la Licencia P£blica General de GNU, un  otra licencia
similar.
*

$OS_NAME$ siempre tuvo como objetivo que los programadores se juntaran a
escribir c¢digo. Consulte la p gina del Proyecto $OS_NAME$ para saber como
puede contribuir a $OS_NAME$.
*

¨Tiene dudas sobre configurar o usar $OS_NAME$? Consulte la lista de correo
FreeDOS-user en la p gina ®Forum¯ del sito web.
