; Language: Slovak (sk)
; File ending: sk
; Codepage: 852
; This translation was created by Google AI.
; Please help the FreeDOS group to improve it.

; HneÔ ako bude hotovì hlavnì text pre tento program, bud£ tieto jazykovo
; çpecifick‚ s£bory z tohto projektu odstr nen‚ a presunut‚ do prekladate–sk‚ho
; projektu FD-NLS. Preklady alebo opravy s£ v¡tan‚. Nebud£ vçak prijat‚
; priamo do vìvoja zdrojov‚ho k¢du tohto projektu.

VERSION=%0 (verzia %1)
LICENSE=BSD 3-Clause License
COPYRIGHT=Copyright (c) %1, %0
RIGHTS=Vçetky pr va vyhraden‚.

; Ak chcete uviesœ svoje meno pri preklade zobrazenom v programe, jednoducho
; upravte pole LANGUAGE a vyplåte pole TRANSLATOR. :-)

LANGUAGE=SlovenŸina
TRANSLATOR=

THANKS=Zvl çtne poÔakovanie %0 za poskytnutie prekladov do jazyka %1.

; T to hra m  ve–mi m lo textu a ve–a pr zdneho miesta na obrazovke. Preto
; çtandardne pou§¡va v„Ÿçie anglick‚ p¡smo 12x14. V tomto p¡sme zaber  riadok
; HINT v„Ÿçinu ç¡rky obrazovky. Pre in‚ jazyky s£ vçak najv„Ÿçie p¡sma
; 10x12 alebo 8x16. Tieto jazykovo çpecifick‚ fonty n jdete na FD-NLS v
; adres ri "danger".

LEVEL=Sekvencia
TRIES=Pokusy
START=kliknite alebo stlaŸte kl ves
DEATH=nespr vne
GAMEOVER=koniec hry

; Ak je v ç preklad HINT ove–a dlhç¡, bude pravdepodobne orezanì. Zv §te
; vynechanie odkazu na numerick£ kl vesnicu. Mo§no ho prelo§te len ako
; "pou§ite ç¡pky alebo myç".

HINT=pou§ite ç¡pky, numerick£ kl vesnicu alebo myç

ERROR.MOUSE=nepodarilo sa n jsœ myç. Je skutoŸne nevyhnutn .
ERROR.VIDEO=nepodarilo sa n jsœ §iadny vhodnì grafickì ovl daŸ

ERROR.DRIVER.FIND=nemo§no n jsœ ovl daŸ %0
ERROR.DRIVER.INIT=nemo§no inicializovaœ ovl daŸ %0
ERROR.DRIVER.MODE=otv ranie grafick‚ho ovl daŸa %0 re§im %1

ERROR.NOHELP=pomocn¡k nie je k dispoz¡cii
ERROR.FORMAT=nepodarilo sa rozpoznaœ form t s£boru %0

; Je mo§nìch mnoho Ôalç¡ch chybovìch hl sen¡/k¢dov. Tie by sa vçak mali
; vyskytovaœ len zriedka. Preto bola v„Ÿçina vynechan . Z tìch zvyçnìch
; by sa mali skutoŸne vyskytn£œ iba pri kompil cii v re§ime "Debug".

ERROR.1=neplatn  funkcia
ERROR.2=s£bor sa nenaçiel
ERROR.3=cesta sa nenaçla
ERROR.4=pr¡liç ve–a otvorenìch s£borov
ERROR.5=pr¡stup k s£boru odmietnutì
ERROR.8=nedostatok pam„te
ERROR.201=kontrola rozsahu £dajov
ERROR.202=preteŸenie z sobn¡ka
ERROR.203=preteŸenie pam„te
ERROR.204=oper cia s ukazovate–om
ERROR.220=kontrola d tov‚ho typu
ERROR.221=nepodporovan  oper cia
ERROR.222=neplatnì form t s£boru
ERROR.223=çtrukt£ra je pr¡liç ve–k 
ERROR.224=overenie £dajov
ERROR.225=nepriradenì ukazovate–
ERROR.226=uvo–nenie uzamknut‚ho prostriedku
ERROR.227=chyba komprimovan‚ho obrazu
ERROR.230=chyba inicializ cie
ERROR.231=nespr vne zarovnanì ovl daŸ
ERROR.232=nepodporovanì typ ovl daŸa
ERROR.233=neplatnì typ ovl daŸa
ERROR.234=overenie ovl daŸa
ERROR.240=zlyhanie grafick‚ho ovl daŸa
ERROR.241=zlyhanie zvukov‚ho ovl daŸa
ERROR.242=zlyhanie ovl daŸa kl vesnice
ERROR.243=zlyhanie ovl daŸa myçi
ERROR.244=zlyhanie ovl daŸa joysticku

