# Language: slovak
# File ending: sk
# Codepage: cp852
# This translation was made by Google AI, please help the
# FreeDOS group to improve it.

NAME

CHOICE - Cak , kìm pou§¡vatel stlac¡ kl ves zo zoznamu volieb

SYNOPSIS

CHOICE [/B] [/C[:]volby] [/N] [/S] [/T[:]c,nn] [text]

OPTIONS

/B
Vyd  zvukov‚ upozornenie (p¡pnutie) pri vìzve.

/C[:]volby
æpecifikuje povolen‚ kl vesy vo vìzve. Ked sa zobrazia, kl vesy bud£
oddelen‚ ciarkami, zobrazen‚ v hranatìch z tvork ch ([]) a nasledovan‚
ot znikom. Ak neuvediete prep¡nac /C, CHOICE pou§ije ako predvolen‚ AN.
Dvojbodka (:) je voliteln .

/N
Sp“sob¡, §e CHOICE nezobraz¡ vìzvu. Text pred vìzvou sa vçak st le
zobraz¡. Ak uvediete prep¡nac /N, çpecifikovan‚ kl vesy s£ st le platn‚.

/S
Sp“sob¡, §e CHOICE bude rozliçovat velk‚ a mal‚ p¡smen . Ak prep¡nac /S
nie je uvedenì, CHOICE prijme velk‚ aj mal‚ p¡smen  kl vesov, ktor‚
pou§¡vatel zad .

/T[:]c,nn
Sp“sob¡, §e CHOICE pock  zadanì pocet sek£nd, kìm sa predvolene
vyberie zadanì kl ves. Hodnoty pre prep¡nac /T s£ nasleduj£ce:

   c   æpecifikuje znak, ktorì sa m  predvolene vybrat po nn sekund ch.
       Znak mus¡ byt v sade volieb çpecifikovanej prep¡nacom /C.

   nn  æpecifikuje pocet sek£nd cakania. Prijateln‚ hodnoty s£ od 0 do 99.
       Ak je zadan‚ 0, nebude §iadna pauza pred predvolenìm vìberom.

text
Textovì retazec, ktorì sa m  zobrazit ako vìzva

RETURN VALUE

ERRORLEVEL je nastavenì na index kl vesu, ktorì pou§¡vatel stlacil vo volb ch.

AUTHOR

Jim Hall, jhall@freedos.org

