# Language: slovakian
# File ending: sk
# Codepage: 852
# This translation was made by Google AI,
# please help the FreeDOS group to improve it.

# common to many functions [Set 1]
1.1:\n
# main [Set 1] 
1.2:Vìpis CESTY k adres ru\n
# Must include %s for label 
1.3:Vìpis CESTY k adres ru pre zv„zok %s\n
# Must include %s for serial #  
1.4:S‚riov‚ Ÿ¡slo zv„zku je %s\n
1.5:Neexistuj£ §iadne podadres re\n\n
# showUsage [Set 2] 
2.1:Graficky zobraz¡ çtrukt£ru adres rov jednotky alebo cesty.\n
# Each %c below will be replaced with proper switch/option
2.2:TREE [jednotka:][cesta] [%c%c] [%c%c]\n
2.3:   %c%c   Zobraziœ men  s£borov v ka§dom adres ri.\n
2.4:   %c%c   Pou§iœ ASCII namiesto rozç¡renìch znakov.\n
# showInvalidUsage [Set 3] 
# Must include the %s for option given.
3.1:Neplatnì prep¡naŸ - %s\n
# The %c will be replaced with the primary switch (default is /)
3.2:Pre n povedu pou§ite TREE %c?.\n
#showTooManyOptions
3.3:Pr¡liç ve–a parametrov - %s\n
# showVersionInfo [Set 4] 
# also uses treeDescription, message 2.1
4.1:Nap¡san‚ pre pr cu s FreeDOS\n
4.2:Win32(c) konzola a DOS s podporou LFN.\n
# Must include the %s for version string. 
4.3:Verzia %s\n
4.4:Autor:       Kenneth J. Davis\n
4.5:D tum:       August-November 2000; Janu r 2001\n
4.6:Kontakt:     jeremyd@computer.org\n
4.7:Copyright (c): Public Domain [defin¡cia USA]\n
#4.8 is only used when cats support is compiled in.
4.8:Pou§¡va kni§nicu Cats Jima Halla <jhall@freedos.org>\n  Copyright (C) 1999,2000,2001 Jim Hall\n
#4.20 20-30 reserved for FreeDOS tree derived from Dave Dunfield's tree
4.20:Copyright 1995, 2000 Dave Dunfield - vo–ne ç¡rite–n‚ (2000 vydan‚ pod GPL).\n
# showInvalidDrive [Set 5] 
5.1:Neplatn  çpecifik cia jednotky\n
# showInvalidPath [Set 6] 
# Must include %s for the invalid path given. 
6.1:Neplatn  cesta - %s\n
# misc error conditions [Set 7]
# showBufferOverrun
# %u required to show what the buffer's current size is. 
7.1:Chyba: Cesta k s£boru prekraŸuje limit vyrovn vacej pam„te = %u bajtov\n
# showOutOfMemory
# %s required to display what directory we were processing when ran out of memory.
7.2:Nedostatok pam„te v podadres ri: %s\n
#
# parseArguments [Set 8]
8.1:/
8.2:-
8.3:F
8.4:f
8.5:A
8.6:a
8.7:V
8.8:v
8.9:S
8.10:s
