# Language: Slovak (slowakisch)
# File ending: sk
# Codepage: 852
# Translation made by Google Gemini
# This translation was made by Google AI, please help the
#  FreeDOS group to improve it.


0.0:Zobrazuje obsah textov‚ho s£boru po jednej obrazovke
0.1:Pou§itie
0.2:pr¡kaz
0.3:s£bor
0.4:Dostupn‚ kl vesy
0.5:Nn
0.6:Òalç¡ s£bor
0.7:Qq
0.8:UkonŸiœ program
0.9:Medzern¡k
0.10:Òalçia str nka
1.0:Nerozpoznan  vo–ba
1.1:S£bor neexistuje
1.2:Nemo§no otvoriœ s£bor
2.0:Viac
2.1:<STDIN>

1.3:vo–ba /Tabs mus¡ byœ /T1..9 (predvolen‚ 4)
