# Language: Slovak
# File ending: SK
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

SYSLINUX

SYSLINUX je kolekcia zav dzaŸov (bootloaders)

Inçtal cia:
SYSLINUX C:
COPY MEMDISK C:\
COPY CHAIN.C32 C:\
COPY MENU.C32 C:\

Pri sp£çœan¡, keÔ sa zobraz¡ pr¡kazovì riadok, nap¡çte
CHAIN.C32 FREEDOS=KERNEL.SYS

Pr¡padne vytvorte s£bor SYSLINUX.CFG, k tomu si pozorne preŸ¡tajte
dokument ciu! (v ni§çie uvedenom pr¡klade adres r "CONTENTS", v åom adres r
ISOLINUX, v åom zav dzaŸ CD-ROM ISOLINUX.BIN - re§im bez emul cie.
dbajte na to, aby ste pou§¡vali "/" a "\" presne tak, ako je uveden‚ ni§çie!

Pre MEMDISK a ISOLINUX si pros¡m pozorne preŸ¡tajte dokument ciu!:
* mkisofs -b isolinux/freedos.img -o c:\cdtest\cd1.iso contents
* mkisofs -no-emul-boot -b isolinux/isolinux.bin -o c:\cdtest\cd1.iso
  contents

Alternat¡vy k CDRECORD (ktorì obsahuje MKISOFS) s£ XORRISO a CDRKIT
(pozri http://sites.google.com/site/blairdude/cdrkit pre DOS port)

