# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vstr [options]

Jednoduchì n stroj na spracovanie reœazcov. Vypisuje vìsledky na STDOUT.

    /N          Nezapisovaœ CRLF po dokonŸen¡.
    /U          Vstupnì filter: Previesœ na ve–k‚ p¡smen .
    /D          Vstupnì filter: Previesœ na mal‚ p¡smen .
    /B          Vstupnì filter: Ignorovaœ pr zdne riadky.
    /I          Vstupnì filter: Ignorovaœ odsadenie.
    /C code     Zap¡saœ k¢d znaku ASCII.
    /R times    Opakovaœ Ôalç¡ z pis times kr t. (1-65535)
    /L line     Vr tiœ iba t£to line zo çtandardn‚ho vstupu. (0-65535)
                (Pozn mka: vline /L TOTAL vr ti celkovì poŸet riadkov.)
                Pridanie :n tie§ vyp¡çe n riadkov.
    /S s1 s2    N jsœ a nahradiœ vçetky vìskyty s1 za s2.
    /F s1 s2    Nastaviœ odde–ovaŸ na s1 a vr tiœ len poz¡ciu po–a alebo
                rozsah s2.
    /A code s2  Vr tiœ code oddelen£ poz¡ciu po–a alebo rozsah s2.
                (tab=0x09)
    /P s1       VytlaŸiœ text s1.
    /T file ID  Vyh–adaœ ID v file a spracovaœ ako vo–by pr¡kazov‚ho
                riadka. Ak‚ko–vek Ôalçie vo–by za tìmto prep¡naŸom sa
                pou§ij£ na naplnenie premennìch %1-%9 v reœazci.

    tba         (St le vo vìvoji, Ôalçie bud£ ozn men‚)
