# Language: Slovak
# File ending: SK
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

1.0:An
1.1:\040:\040
1.2:O.K.?\040
1.3:Chyba vstupu
1.4:%s: naŸ¡tanì %lu riadok\n
1.5:%s: naŸ¡tanìch %lu riadkov\n
1.6:%s: zap¡sanì %lu riadok\n
1.7:%s: zap¡sanìch %lu riadkov\n
1.8:%lu:%c%s\n
1.9:StlaŸte <Enter> pre pokraŸovanie
1.10:%lu:\040
1.11:Nen jden‚
1.12:%lu: %s\n
1.13:\nedlin m  nasleduj£ce podpr¡kazy:\n
1.14:#                 upraviœ jeden riadok    [#],[#],#m        presun£œ
1.15:a                 pridaœ                  [#][,#]p          str nka
1.16:[#],[#],#,[#]c    kop¡rovaœ               q                 ukonŸiœ
1.17:[#][,#]d          zmazaœ                  [#][,#][?]r$,$    nahradiœ
1.18:e<>               koniec (ulo§iœ & skonŸiœ) [#][,#][?]s$      h–adaœ
1.19:[#]i              vlo§iœ                  [#]t<>            preniesœ
1.20:[#][,#]l          vylistovaœ              [#]w<>            zap¡saœ\n
1.21:kde vyççie uveden‚ $ je reœazec, <> je n zov s£boru,
1.22:# je Ÿ¡slo (m“§e byœ . = aktu lny riadok, $ = poslednì riadok,
1.23:alebo Ÿ¡slo + Ÿi - in‚ Ÿ¡slo).\n
1.24:, copyright (c) 2003 Gregory Pietsch
1.25:This program comes with ABSOLUTELY NO WARRANTY.
1.26:It is free software, and you are welcome to redistribute it
1.27:under the terms of the GNU General Public License -- either
1.28:version 2 of the license, or, at your option, any later
1.29:version.\n
1.30:Nedostatok pam„te
1.31:Chyba d’§ky reœazca
1.32:Chyba poz¡cie reœazca
1.33:Neplatnì vstup, pou§ite ? pre n povedu.
1.34:Chìba n zov s£boru
1.35:Vyrovn vacia pam„œ je pr¡liç ve–k 
1.36:Neplatn  poz¡cia vo vyrovn vacej pam„ti
1.37:CHYBA: %s\n

# END OF FILE
