# Language: slovakian
# File ending: sk
# Codepage: 852
# This translation was made by Google AI,
# please help the FreeDOS group to improve it.

FC v. 3.03 (c) 2004 Maurizio Spagni

FC porovn va dva s£bory alebo sady s£borov v textovom alebo bin rnom re§ime
a zobrazuje rozdiely medzi nimi.

FC implementuje algoritmus Paula Heckela z Communications of the
Association for Computing Machinery, apr¡l 1978, s. 264 - 268,
"Technika na izol ciu rozdielov medzi s£bormi".

Tento algoritmus m  oproti be§nejç¡m porovn vac¡m algoritmom vìhodu v tom,
§e je rìchly a dok §e detegovaœ rozdiely v –ubovo–nom poŸte riadkov. Vo
v„Ÿçine aplik ci¡ algoritmus izoluje rozdiely podobne ako met¢da najdlhçej
spoloŸnej podpostupnosti.

Syntax je nasledovn :

FC [prep¡naŸe] [jednotka1:][cesta1]s£bor1 [jednotka2:][cesta2]s£bor2

 /A    Zobraziœ iba prvì a poslednì riadok pre ka§d£ sadu rozdielov
 /B    Vykonaœ bin rne porovnanie
 /C    Ignorovaœ ve–kosœ p¡smen
 /L    Porovnaœ s£bory ako text ASCII
 /LBn  Nastaviœ max. poŸet po sebe id£cich rozdielnych ASCII riadkov na n
 /Mn   Nastaviœ maxim lny poŸet rozdielov v bin rnom porovnan¡ na n bajtov
 /N    Zobraziœ Ÿ¡sla riadkov pri textovom porovnan¡
 /Q    Nezobrazovaœ zoznam rozdielov
 /R    Zobraziœ struŸn£ z vereŸn£ spr vu (v§dy akt¡vne pri pou§it¡ /S)
 /S    Rozç¡riœ skenovanie na s£bory v podadres roch
 /T    Neprev dzaœ tabul tory na medzery
 /U    Zobraziœ n zvy s£borov, ktor‚ nemaj£ n protivok
 /W    Zkomprimovaœ biele znaky (tabul tory a medzery) pre porovnanie textu
 /X    Nezobrazovaœ kontextov‚ riadky pri textovom porovnan¡
 /nnn  Nastaviœ min. poŸet po sebe id£cich zhodnìch riadkov na nnn
       pre op„tovn£ synchroniz ciu porovnania

Program podporuje dlh‚ n zvy s£borov (LFN) a pou§¡va ich automaticky, ak
ich operaŸnì syst‚m podporuje.

FC sa predvolene prepne do bin rneho re§imu pri s£boroch .EXE, .COM, .SYS,
.OBJ, .BIN, .DLL a .LIB.

V bin rnom re§ime FC zobrazuje offset rozdielnych bajtov v s£bore, ich
hexadecim lnu hodnotu a (ak s£ tlaŸite–n‚) ich znak ASCII.

Predvolene sa bin rne porovn vanie zastav¡ po 20 rozdieloch, ale t£to
hodnotu mo§no zmeniœ prep¡naŸom /M. /M0 znamen  "neobmedzene".
/M sa interpretuje ako /M0.

Obmedzen¡m programu je, §e v textovom re§ime sa porovn va iba prvìch
32765 riadkov; zvyçn‚ riadky s£ ignorovan‚. D’§ka riadka je prakticky
neobmedzen .

FC podporuje z stupn‚ znaky (wildcards). P r slov k tomu:
- urŸenie adres ra je rovnak‚ ako urŸenie vçetkìch s£borov v åom ("*.*").
  Pr¡klad: "FC C:\ A:" je to ist‚ ako "FC C:\*.* A:*.*"
- ak nie je zadanì s£bor2, predpoklad  sa "." (aktu lny adres r).
  Pr¡klad: "FC C:\SUBOR.TXT" je to ist‚ ako "FC C:\SUBOR.TXT .\*.*"
- ak m  s£bor1 z stupn‚ znaky, ale s£bor2 nie, vçetky s£bory zodpovedaj£ce
  s£boru1 sa porovnaj£ s tìm istìm s£borom2.
- ak m  s£bor1 z stupn‚ znaky a s£bor2 je cesta s "*.*", vçetky s£bory
  zodpovedaj£ce s£boru1 sa porovnaj£ so s£bormi rovnak‚ho mena v ceste s£bor2.
- ak maj£ oba s£bory z stupn‚ znaky, porovnaj£ sa s£bory v ceste s£boru1
  s pr¡sluçnìm s£borom v ceste s£boru2. Pr¡klad: "FC *.TXT STARE\*.BAK"
Je to jednoduchçie urobiœ ako vysvetliœ. Ak chcete porovnaœ ka§dì s£bor
v adres ri so vçetkìmi v inom: FC *.* MOJADR\????????.???

Vo–ba /S opakuje rovnakì vzor h–adania v podadres roch s rovnakìm n zvom.
  Pr¡klad: "FC /S C:*.TXT D:*.BAK"
  Ak existuj£ adres re C:\KNIHA a D:\KNIHA, tento pr¡kaz porovn  vçetky
  *.TXT v aktu lnych adres roch a tie§ vçetky KNIHA\*.TXT.

N vratov‚ k¢dy ERRORLEVEL s£ nasledovn‚:
	0	Vçetky s£bory sa zhoduj£
	1	Aspoå jeden p r s£borov sa l¡çi
	2	Neplatnì parameter na pr¡kazovom riadku
	3	S£bor sa nenaçiel
	4	Chyba pri otv ran¡ s£boru (s£borov)
