# Language: Slovak
# File ending: SK
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

CD.INIT=Inicializ cia CD-ROM.
CD.GIVEUP=/p /fLightRed "nemo§no naŸ¡taœ vhodnì ovl daŸ CD/DVD" /fGrey
CD.ERROR=, /fGrey chyba "#%1" - /fLightRed zlyhalo /fGrey /p
CD.NO_DRVR= /fGrey nemo§no n jsœ ovl daŸ CD /fYellow "%1" /fGrey - /fLightRed zlyhalo /fGrey
CD.TRY_DRVR= /g pokus o pou§itie ovl daŸa CD /fYellow "%1" /fGrey
CD.TRY_CACHE= /g pokus o naŸ¡tanie /fYellow "%1" /fGrey pre vyrovn vaciu pam„œ
CD.TRY_EXT= pokus o naŸ¡tanie rozç¡ren¡ CD /fYellow "%1" /fGrey
CD.SUCCESS=, /fLightGreen £spech /fGrey
CD.STATUS=ovl daŸ CD a rozç¡renia pre jednotku /fLightGreen "%1" /fDarkGrey (%2) /fGrey boli £speçne spusten‚

CD.DRIVE=CD-ROM konfigurovanì ako jednotka /fLightGreen %1 /fGrey /fDarkGrey (%2) /fGrey
CD.NONE=/fLightRed CD-ROM nie je konfigurovanì /fGrey

NO_HELP=nemo§no n jsœ s£bor pomocn¡ka
