# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vask [vo–by]

Vìzva na zadanie textu.

    [§iadne]    Pou§iœ zisten‚ nastavenia pre vstup.
    [text]      Prednastavenì upravenì text.
    /S          Poskytuje jednoduchì vìber znakov. Ako çtandardnì choice.
                Pri pou§it¡ vask vracia iba errorlevel vìberu.
    /A n        Nastaviœ atrib£t textu na n.
    /B farba    Nastaviœ atrib£t pozadia textu na farbu (alebo hodnotu).
    /F farba    Nastaviœ atrib£t popredia textu na farbu (alebo hodnotu).
    /G          Zadaœ text glob lne a ignorovaœ ak‚ko–vek r movanie.
    /L          Zadaœ text lok lne s oh–adom na r movanie. (PREDVOLEN)
    /K n        Pou§iœ n namiesto znaku r mu na detekciu hran¡c.
    /C          Ak je zadan‚ a stlaŸ¡ sa Control-C, ukonŸ¡ sa s errorlevel
                200 a vr ti predvolen£ hodnotu.
    /W ç¡rka    Prep¡saœ predvolen£ ç¡rku pruhu.
                (predvolen‚ je od kurzora na koniec riadka)
    /T s£bor ID Vyh–adaœ ID v s£bore a spracovaœ ako vo–by pr¡kazov‚ho
                riadka. Òalçie vo–by za tìmto prep¡naŸom naplnia
                premenn‚ %1-%9 v textovom reœazci.
    /D sekundy  Oneskorenie v sekund ch, kìm vìzva vyprç¡ a
                vr ti poŸiatoŸn£ predvolen£ hodnotu. (vracia errorlevel 1)

    tba         (St le vo vìvoji, Ôalçie bud£ ozn men‚)
