# Help Message
# Language: Slovak (slowakisch)
# Codepage: 852, sk
# Translation made by Google Gemini

0.0:Presun£œ
0.1:Presunie s£bor/adres r do in‚ho umiestnenia.
0.2:(C) 1997-2002 Joe Cosentino
0.3:(C) 2003-2004 Imre Leber
0.4:Syntax: MOVE
0.5:zdroj1[, zdroj2[,...]] cie–
0.6: zdroj       N zov s£boru alebo adres ra, ktorì chcete presun£œ
0.7: cie–        Miesto, kam chcete s£bor(y) presun£œ
0.8:             PotlaŸ¡ vìzvu na potvrdenie prep¡sania
0.9:             existuj£ceho cie–ov‚ho s£boru.
0.10:            Vyvol  vìzvu na potvrdenie prep¡sania
0.11:            existuj£ceho cie–ov‚ho s£boru.
0.12:            Over¡ ka§dì s£bor pri z pise do cie–ov‚ho s£boru,
0.13:            aby sa zaistilo, §e cie–ov‚ s£bory s£ identick‚ so
0.14:            zdrojovìmi s£bormi
0.15:Pozn mka:
0.16:Pomocou tohto n stroja m“§ete pres£vaœ adres re

# Various messages

1.0:neexistuje!
1.1:u§ existuje!
1.2:Prep¡saœ s£bor
1.3:Probl‚m pri presune adres ra
1.4:Probl‚m pri presune s£boru
1.5:Neplatnì parameter
1.6:Neplatn  çpecifik cia zdrojov‚ho disku
1.7:Neplatnì cie–ovì s£bor
1.8: neexistuje ako adres r. Vytvoriœ ho?
1.9:Neplatnì zdrojovì s£bor
1.10:Nemo§no vytvoriœ adres r
1.11:S£bor nemo§no skop¡rovaœ na seba sam‚ho
1.12:Nemo§no presun£œ s£bor do adres ra
1.13:S£bor u§ existuje
1.14:S£bor nemo§no skop¡rovaœ na seba sam‚ho
1.15:Pr¡stup odmietnutì
1.16:Nedostatok miesta na disku v cie–ovej ceste
1.17:Nedostatok miesta na disku
1.18:Chìba povinnì parameter
1.19:Neplatn  çpecifik cia zdroja
1.20:Zdrojov  cesta nebola n jden 
1.21:Zdrojov  cesta je pr¡liç dlh \n
1.22:Cie–ov  cesta je pr¡liç dlh \n
1.23:Neplatn  çpecifik cia cie–ov‚ho disku\n
1.24:Cie–ov  cesta je pr¡liç dlh \n
1.25:Nemo§no otvoriœ zdrojovì s£bor
1.26:Nemo§no vytvoriœ cie–ovì s£bor
1.27:Chyba pri z pise do cie–ov‚ho s£boru
1.28:Nemo§no vytvoriœ adres r
1.29:Nedostatok miesta na disku v cie–ovej ceste
1.30:Nedostatok pam„te

# Y/N/All/None; Simple messages

2.0:A
2.1:N
2.2:V
2.3:Z
2.4:ok
