# Language: Slovak (sk)
# File ending: sk
# Codepage: 852
# This translation was created by Google AI.
# Please help the FreeDOS group to improve it.

FDTUI

Shell textov‚ho pou§¡vate–sk‚ho rozhrania pre FreeDOS

Copyright (C) 2017-2022 Ercan Ersoy
Tento program je slobodnì softv‚r. (GNU General Public License verzia 2)
                                   (GNU General Public License verzia 3)

Tento projekt obsahuje kni§nicu FDOSTUI. FDOSTUI m  vlastn‚ licencie.
Tento projekt obsahuje kni§nicu Kitten. Kitten m  vlastn£ licenciu.


VÔaka:

* VÔaka pou§¡vate–ovi Atnode za franc£zske preklady.
* VÔaka pou§¡vate–ovi Berki Yenign za franc£zske preklady.
* VÔaka pou§¡vate–ovi Ericovi Auerovi za kni§nicu Kitten.
* VÔaka projektu FLTK za kni§nicu FDOSTUI.
* VÔaka pou§¡vate–ovi Jeromeovi Shidelovi za kni§nicu FDOSTUI.
* VÔaka pou§¡vate–ovi Jimovi Hallovi za kni§nicu Kitten.
* VÔaka pou§¡vate–ovi Markovi Olesenovi za niektor‚ zmeny k¢du a
  kni§nicu FDOSTUI.
* VÔaka pou§¡vate–ovi Parodper za çpanielske preklady.
* VÔaka pou§¡vate–ovi Sebastianovi Rasmussenovi za çv‚dske preklady.
* VÔaka pou§¡vate–ovi Tomovi Ehlertovi za kni§nicu Kitten.
* VÔaka pou§¡vate–ovi Wilhelmovi Spieglovi za nemeck‚ preklady.


Kompil cia:

  Tento softv‚r by mal byœ kompilovanì pomocou Open Watcom.

Prispievanie:

  Ak chcete prispieœ k tomuto projektu, m“§ete nahl siœ pr¡padn‚ chyby a
  vytvoriœ pull request v repozit ri FDTUI.


Zmeny (Changelog):

* 0.8 (19.02.2022)
  * Aktualizovanì n zov spustite–n‚ho s£boru.
  * Aktualizovanì n zov prekladovìch s£borov.
  * Aktualizovanì Makefile pre pou§itie premennej "EXE".
  * Aktualizovan  kni§nica FDOSTUI.
  * Odstr nen‚ objektov‚ s£bory z kni§n¡c tret¡ch str n FDTUI a pridan‚
    kompilaŸn‚ direkt¡vy pre kompil ciu kni§n¡c tret¡ch str n.
  * Opraven‚ varovanie pr¡znaku kl vesu ESC.
  * Pridan‚ çv‚dske preklady.
  * Aktualizovan‚ inform cie o copyrighte.
  * Aktualizovanì sn¡mka obrazovky.
  * Aktualizovanì zoznam zmien.

* 0.7 (26.12.2021)
  * Pridan‚ nemeck‚ preklady.
  * Pridan‚ çpanielske preklady.
  * Aktualizovan‚ inform cie o copyrighte v s£bore README.md.
  * Aktualizovan  sekcia vÔaky v s£bore README.md a v s£boroch README.
  * Aktualizovanì zoznam zmien.

* 0.6 (20.12.2021)
  * Aktualizovan‚ franc£zske preklady.
  * Aktualizovan‚ zobrazenie atrib£tov polo§iek v spr vcovi s£borov.
  * Aktualizovan‚ inform cie n povedy.
  * Aktualizovan‚ inform cie o copyrighte v s£boroch README.
  * Aktualizovanì sn¡mka obrazovky.
  * Aktualizovanì zoznam zmien.

* 0.5 (20.09.2020)
  * Opraven‚ niektor‚ typografick‚ chyby vo franc£zskych prekladoch a v
    tureckom README.
  * Aktualizovan‚ franc£zske preklady.
  * Pridanì novì franc£zsky s£bor README.
  * Aktualizovanì zoznam zmien.

* 0.4 (28.05.2020)
  * N zov tohto softv‚ru zmenenì na "FDTUI".
  * Opraven‚ inform cie n povedy pre lokaliz ciu.
  * Opraven‚ niektor‚ typografick‚ chyby.
  * Aktualizovan‚ franc£zske preklady.
  * Aktualizovanì s£bor .gitignore.
  * Odstr nenì spustite–nì s£bor zo zdrojov.
  * Aktualizovan‚ s£bory LICENSE, README.md, anglick‚ a tureck‚ README.
  * Odstr nenì franc£zsky s£bor README.
  * Aktualizovanì zoznam zmien.

* 0.3 (09.12.2018)
  * Zmenen  farebn  sch‚ma.
  * Zmenen‚ ponuky panela.
  * Aktualizovan‚ jazykov‚ s£bory.
  * Zmazanì nepotrebnì riadok v s£bore DOSSHELL.FR.
  * Opraven‚ zaçkrt vacie pol¡Ÿka "Zobraziœ arch¡vne polo§ky" a
    "Zobraziœ skryt‚ polo§ky" v spr vcovi s£borov.
  * Kl ves ESC deaktivovanì.
  * Zmenenì directory strom.
  * Opraven‚ niektor‚ typografick‚ chyby.
  * Opraven  chyba vìberu zoznamu ovl daŸov pomocou kl vesnice.
  * Opraven  chyba, kedy sa nezobrazovali atrib£ty polo§iek pri zmene
    drive a chyby pri otv ran¡ spr vcu s£borov.
  * Rozdelen‚ hlaviŸkov‚ s£bory a zdrojov‚ s£bory.
  * Opravenì parameter n povedy.
  * Zmenen‚ pr¡pony hlaviŸkovìch s£borov z ".h" na ".hpp".
  * Mazanie obrazovky nahraden‚ çtandardnou funkciou Open Watcom
    namiesto pr¡kazu CLS.
  * Opraven‚ vçetky varovania.
  * Pridan‚ inform cie o licencii GNU GPL verzia 2.
  * Aktualizovanì zoznam zmien.

* 0.2 (24.09.2018)
  * Farba p¡sma deaktivovanìch polo§iek menu zmenen  na siv£ (predtìm
    vyzerala ako Ÿerven ).
  * Predvolen‚ nastavenie pre zobrazenie arch¡vnych polo§iek a polo§iek
    iba na Ÿ¡tanie zmenen‚ na "povolen‚".
  * Pridan  pauza na koniec pr¡kazu pri sp£çœan¡ pr¡kazov.
  * Aktualizovan‚ anglick‚ a tureck‚ preklady.
  * V niektorìch s£boroch pou§it‚ spr vne znaky nov‚ho riadka namiesto
    nespr vnych.
  * Aktualizovanì zoznam zmien.

* 0.1 (13.07.2018)
  * Vytvoren  prv  verzia.


Pozn mka:

* FreeDOS is a trademark of Jim Hall.
