# Language: Slovak
# File ending: SK
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

TITLE=Enhanced Disk Image Creation Tool, verzia %_ %s
COPYRIGHT=Copyright (c) 2018, Jerome Shidel

HELP_00="Inform cie o vo–b ch EDICT: "
HELP_01=
HELP_02="  /d <jednotka>  urŸenie p¡smena jednotky"
HELP_03="  /f <n zov_s£b> urŸenie n zvu s£boru"
HELP_04="  /p <limit>     obmedzenie maxim lneho poŸtu dodatoŸnìch prechodov"
HELP_05=
HELP_06="  /t <typ>       prep¡saœ BIOS a vybraœ nastavenia pre typ disku"
HELP_07="                 (0=360Kib, 1=1.2Mib, 2=720Kib, 3=1.44Mib, a=auto)"
HELP_08=
HELP_09="  /c <Ÿ¡slo>     prep¡saœ poŸet valcov/st“p (0-1023)"
HELP_0a="  /r <Ÿ¡slo>     prep¡saœ poŸet str n/hl v na stopu (0-255)"
HELP_0b="  /s <Ÿ¡slo>     prep¡saœ poŸet sektorov na stranu (0-63)"
HELP_0c="  /b <Ÿ¡slo>     prep¡saœ poŸet bajtov na sektor (1-8192)"
HELP_0d=
HELP_0e="  /h             zobrazenie n povedy"

HELP_??="  /T             test iba na Ÿ¡tanie"
HELP_??="  /w             z pis obrazu na disketu"
HELP_??="  /v             overenie diskety"
HELP_??="  /i             iba inform cie"
HELP_??="  /o             iba jeden sektor"
HELP_??="  /q             tichì re§im"
HELP_??="  /e             pokraŸovaœ z existuj£ceho s£boru obrazu"
HELP_??="  /m <n zov_s£b> pripojiœ s£bor obrazu (mount)"
HELP_??="  /u             odpojiœ s£bor obrazu (unmount)"
HELP_??="  /l             zoznam typov diskov"

INVALID=%r "Neplatnì pr¡kaz: `" %s "'"
BAD_INT="Neplatn  Ÿ¡seln  hodnota."
BAD_VAL="Hodnota je mimo rozsahu."

DRIVE=Jednotka %_ %c: (ID 0x %b ) %_
DRIVE_TYPE=%_ (ID 0x %b )
DRIVE_TYPE_00=nezn my typ jednotky
DRIVE_TYPE_01='5.25"' 360Kib jednotka
DRIVE_TYPE_02='5.25"' 1.2Mib jednotka
DRIVE_TYPE_03='3.5"' 720Kib jednotka
DRIVE_TYPE_04='3.5"' 1.44Mib jednotka
DRIVE_TYPE_05=inì typ jednotky

DRIVE_SPEC=%i %_ bajtov, %_ %I %_ sektorov, %_ %I %_ st“p, %_ %I %_ str n(y)

PASS_LIMIT=Povolenìch a§ %_ %i %_ extra prechodov na Ÿ¡tanie diskety
BUFFERS=%i %_ bajtovì buffer diskety, %_ %i %_ bajtovì buffer vìsledkov stopy

PASS=Prechod Ÿ¡tania diskety Ÿ. %i. Zost va %_ %i %_ sektorov.

READ_FAST=¬ÖTANIE STOPY: %_ %i, HLAVA: %_ %i
READ_SLOW=¬ÖTANIE STOPY: %_ %i, HLAVA: %_ %i, SEKTOR: %_ %i

FAILED=Proces vytv rania obrazu zlyhal.
ABORTED=Proces vytv rania obrazu bol preruçenì.
COMPLETED=Proces vytv rania obrazu bol dokonŸenì.

BErr=%r "Chybovì k¢d BIOS: 0x" %b %_ --> %_
BErr_01=ovl daŸu bol odovzdanì zlì pr¡kaz
BErr_02=znaŸka adresy nebola n jden  alebo zlì sektor
BErr_03=chyba ochrany proti z pisu na disketu
BErr_04=sektor nebol n jdenì
BErr_05=reset pevn‚ho disku zlyhal
BErr_06=disketa bola vymenen  alebo vybrat 
BErr_07=zl  tabu–ka parametrov pevn‚ho disku
BErr_08=preteŸenie DMA
BErr_09=pr¡stup DMA cez hranicu 64k
BErr_0a=zlì pr¡znak sektora pevn‚ho disku
BErr_0b=zlì valec pevn‚ho disku
BErr_0c=nepodporovan  stopa
BErr_0d=neplatnì poŸet sektorov vo form te pevn‚ho disku
BErr_0e=detegovan  znaŸka adresy d t riaden  pevnìm diskom
BErr_0f=£roveå arbitr §e DMA pevn‚ho disku mimo rozsahu
BErr_10=chyba ECC/CRC pri Ÿ¡tan¡ disku
BErr_11=opravite–n  chyba d t pevn‚ho disku, d ta opraven‚ pomocou ECC
BErr_20=chyba radiŸa
BErr_40=chyba vyh–ad vania (seek failure)
BErr_80=jednotka nie je pripraven 
BErr_aa=pevnì disk nie je pripravenì
BErr_bb=nedefinovan  chyba pevn‚ho disku
BErr_cc=chyba z pisu na pevnì disk na vybranej jednotke
BErr_e0=chyba stavu pevn‚ho disku
BErr_ff=oper cia sp„tn‚ho hl senia (sense) zlyhala

DErr=%r "Chybovì k¢d DOS: 0x" %b %_ --> %_
DErr_01=Neplatn‚ Ÿ¡slo funkcie
DErr_02=S£bor nebol n jdenì
DErr_03=Cesta nebola n jden„
DErr_04=Pr¡liç ve–a otvorenìch s£borov
DErr_05=Pr¡stup odmietnutì
DErr_06=Neplatnì popisovaŸ (handle)
DErr_08=Nedostatok pam„te
DErr_0f=Zadan  neplatn  jednotka
DErr_15=Jednotka nie je pripraven 

