# Language: Slovak (sk)
# File ending: sk
# Codepage: 852
# This translation was created by Google AI.
# Please help the FreeDOS group to improve it.

Pou§itie: SAYSWHO.EXE [vo–by]

    [vo–by]        Iste, akoby ste naozaj potrebovali nejak£ vo–bu

Mysl¡m si, §e t to hra je ove–a lepçia so zvukom. Hra vçak podporuje
iba PC reproduktor. Bohu§ia–, na rozdiel od DOSBoxu a skutoŸn‚ho
hardv‚ru, v„Ÿçina platforiem virtu lnych strojov nepodporuje emul ciu
PC reproduktora.

:-)


