# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

veach [options]

Urobte nieŸo pre ka§d£ polo§ku v zozname.

/S              Zapn£œ triedenie zoznamu.
/L              Zobraziœ obsah zoznamu.
/F file         Pridaœ polo§ky do zoznamu z file.
/I              Pridaœ polo§ky do zoznamu zo çtandardn‚ho
                vstupn‚ho zariadenia.
/D spec         Pridaœ n zvy s£borov zodpovedaj£ce spec do
                zoznamu.
/A +/-          Uprav¡ prep¡naŸ /d tak, aby povolil vçetky
                s£bory a adres re.
/C              KeÔ sa pou§ije prep¡naŸ /x, umo§åuje
                pokraŸovaœ napriek chybe podprocesu.
/X [cmdln]      Spustiœ polo§ku s pr¡kazovìm riadkom a vçetky
                nasleduj£ce prep¡naŸe sa odovzdaj£ podprocesu.
                * sa rozbal¡ na polo§ku, # je poŸet polo§iek
                a @ je index polo§ky. Ak za prep¡naŸom /x
                nenasleduj£ §iadne d ta pr¡kazov‚ho riadku,
                predpoklad  sa *.
tba             (St le vo vìvoji, Ôalçie bud£ ozn men‚)
