## For instructions for translators please look into file HOWTO.TXT
##

#_OK
' <BARVA=!;KLAVESY=a#1;VYZNAM=!1>A<SB>ceptar '
#_OK2
' <BARVA=!;KLAVESY=a#1#2;VYZNAM=!1>A<SB>ceptar '
#_ANO
' <BARVA=!;KLAVESY=s#1;VYZNAM=!1>S<SB>¡ '
#_NE
' <BARVA=!;KLAVESY=n#2;VYZNAM=!2>N<SB>o '
#_CANCEL
<BARVA=!;KLAVESY=a#2;VYZNAM=!3>A<SB>nular
#_CANCEL2
' <BARVA=!;KLAVESY=a#2;VYZNAM=!3>A<SB>nular '
#_POMOC
A<BARVA=!;KLAVESY=y;VYZNAM=!4>y<SB>uda
#_PALETA
<BARVA=!;KLAVESY=p;VYZNAM=!6>P<SB>aleta
#_MIXBAREV
<BARVA=!;KLAVESY=m;VYZNAM=!7>M<SB>ezclador
#_FS_INFO
<BARVA=!;KLAVESY=i;VYZNAM=!8>I<SB>nfo
#_FS_DISK
<BARVA=!;KLAVESY=d;VYZNAM=!9>D<SB>isco
#_ZADAT
E<BARVA=!;KLAVESY=n;VYZNAM=!14>n<SB>trar
#_PRIDEJPOL
<VYZNAM=!17><<---
#_UBERPOL
<VYZNAM=!18>--->>
#_FS_NOVYADRESAR
Cria<BARVA=!;KLAVESY=r;VYZNAM=!19>r<SB>
#_ZPET
<BARVA=!;KLAVESY=vV;VYZNAM=!20>V<SB>olver
#_VPRED
Sigui<BARVA=!;KLAVESY=eE;VYZNAM=!21>e<SB>nte
#_INFO
'Informaci¢n:       ' 
#_DOTAZ
'Pregunta:          '
#_ANONE_DOTAZ
'Pregunta:          '
#_CHYBA
­Error!
#_VLOZ_TEXT
Entrar texto:
#_VYBER_BARVU
Seleccionar color:
#_FS_ADR_JAKSEMAJMENOVAT
'Entrar nombre de directorio'
#_FS_PRO_CTENI
's¢lo lectura, '
#_FS_SKRYTY
'oculto, '
#_FS_SYSTEMOVY
'sistema, '
#_FS_ARCHIVOVAT
'archivado, '
#_FS_ZADNE
ninguna.
#_FS_ZPRAVA
Mensaje:
#_FS_SOUBOR
'Archivo: '
#_FS_VELIKOST
'Tama¤o: ' 
#_FS_B
' B ('
#_FS_KB
' Kb)'
#_FS_B2
' octas'
#_FS_KB2
Kb
#_FS_MB2
Mb
#_FS_GB2
Gb
#_FS_POSL_ZMENA
'éltima modificaci¢n: '
#_FS_ATRIBUTY
'Atributos: '
#_FS_VYBER_SOUBOR
Selecionar un archivo:
#_FS_SOUBORNEVYTVOREN
La archivo no fue criado
#_FS_ADRESARNEVYTVOREN
La directorio no fue criado
#_FS_DISK2
'Lecturas: '
#_FS_DISK3
'Lectura '
#_FS_JMENOVKADISKU
'Etiqueta de disco: '
#_FS_SYSTEMSOUBORU
'Sistema de archivos: '
#_FS_KAPACITA
'Capacidad: '
#_FS_VOLNEHO
'Espacio libre: '
#_FS_SERCISLO
'N£mero serial: '
#_FS_VYBER_NECO
Debe seleccionar un archivo.
#_FS_JEDNOTKA_NEPRIPRAVENA
La lectura no est  preparado.
#_PREPSATSOUBOR
¨Sobreescribir el archivo?
#_VSEPOL
todos los elementos
#_VYBPOL
los elementos seleccionados
#_ZAMPOL
los elementos rechazados
#_VYBINFO
En el panel derecho se enumeran todos los elementos y en
el panel izquierdo el que est  seleccionado.
Puede agregar y borrar elementos con <<Intro>>
Con <<Tab>> puedes cambiar entre paneles
#_VYBINFO2
En el panel izquierdo se muestran los elementos seleccionados y en
el panel derecho, el resto.
La selecci¢n y el borrado se realizan con <<Intro>>
Puedes cambiar entre paneles con <<Tab>>
#_MOUSE_NOT_INSTALLED
No hay dispositivo de rat¢n instalado. Cargar CTMouse o una dispositivo similar.
#_LFB_NOT_AVAILABLE
Su tarjeta gr fica no es compatible con el acceso LFB para el modo deseado.


