; This file is a part of CuteMouse source
; Here are messages in Spanish
; Translated by Diego Rodr¡guez <dieymir@teleline.es>

E_needvga       db 'Sin VGA? Use un CTMOUSE m s antiguo si necesita compatibilidad con EGA RIL',nl,eos
E_error		db nl,'Error: ',eos
E_option	db 'Opci¢n desconocida',eos
E_argument	db 'Par metro de opci¢n incorrecto',eos
E_help		db 5,nl,'Teclee ®CTMOUSE /?¯ para obtener ayuda',eos

E_mousepresent	db 5,'Controlador de rat¢n ya instalado',eos
E_notfound	db 5,'Error: rat¢n no encontrado',eos
;;+E_noIRQ	db 5,'Error: IRQ no detectada',eos

E_nocute	db 1,'­CuteMouse no ha sido instalado!',eos
E_notunload	db 2,'Imposible desinstalar Cutemouse: algunas interrupciones interceptadas...',eos
S_unloaded	db 0,'Cutemouse ha sido desinstalado correctamente...',eos

S_reset		db 'Controlador residente en ',eos
S_installed	db 'Instalado en ',eos
S_atPS2		db 'puerto PS/2',eos
S_atCOM		db 'COM'
com_port	db ?,' ('
S_atIO		db '0000h/IRQ'
IRQno		db ?
S_in		db ') usando protocolo ',eos
S_inMSYS	db 'modo Mouse Systems',eos
S_inMS		db 'modo Microsoft',eos
S_inLT		db 'modo Logitech',eos
S_wheel		db ' (rueda detectada)'
S_CRLF		db nl,eos

Copyright	db nl,'CuteMouse v',CTMRELEASE,' [FreeDOS]',nl,eos
Syntax		label byte
    db 0,'Opciones:',nl
    db '  /V	   - b£squeda inversa: buscar PS/2 despu‚s de puertos en serie',nl
    db '  /P	   - forzar uso de rat¢n PS/2, no probar puertos en serie',nl
    db '  /S[c[i]] - forzar uso de rat¢n serie en puerto COM c (1-4) con IRQ i (1-7)',nl
    db '  /3	   - forzar modo 3-botones si se encontr¢ rat¢n Microsoft o PS/2)',nl
    db '  /O       - activar detecci¢n de rueda PS2 y USB BIOS (puede colgarse)',nl
    db '  /M       - probar antiguo Mouse Systems / Genius para ratones no PnP',nl,nl
    db '  /R[h[v]] - resoluci¢n horizontal/vertical h,v=1-9. Sin argumento o 0',nl
    db '              en h indica resoluci¢n autom tica, sin argumento en v',nl
    db '              indica valor igual a h',nl
    db '  /L	   - rat¢n para zurdos (por defecto para diestros)',nl,nl
;
    db '  /B	   - no instalar si ya hay otro controlador de rat¢n instalado',nl
    db '  /N	   - instala CuteMouse como un nuevo residente, aunque ya estuviese instalado',nl
    db '	     (£til en archivos de comandos que desinstalen CuteMouse al final)',nl
    db '  /W	   - impedir que se instale en un bloque de memoria alto',nl
    db '  /U	   - desinstalar el controlador,eliminar residente de memoria',nl
    db '  /?	   - mostrar esta ayuda',eos
