; Language: Slovak
; File ending: SK
; Codepage: 852
; This translation was made by Google Gemini.
; Please help the FreeDOS group to improve it.

; Miscellaneous DISPLAY loading error messages
errAlready       DB     "DISPLAY je u§ naŸ¡tanì", 0dH, 0aH, "$"
errNoDRDOS       DB     "FD-DISPLAY je nekompatibilnì s touto verziou DR-KEYB", 0dH, 0aH, "$"
sMemAllocatedBuffers
                 DB     "Alokovan‚ vyrovn vacie pam„te: $"
sInTPA           DB     " v TPA, $"
sInXMS           DB     " v XMS$"

; Hardware-driver specific messages
errAcient        DB     "DISPLAY: pre tento typ hardv‚ru je vy§adovanì aspoå adapt‚r EGA", 0dH, 0aH, "$"
errNoCGA         DB     "DISPLAY: adapt‚r CGA nebol n jdenì", 0dH, 0aH, "$"
errDrvSpecific   DB     "DISPLAY: Kritick  chyba çpecifick  pre ovl daŸ", 0dH, 0aH, "$"

; Command line parsing error messages
SyntaxErrorStr:         DB      "Syntaktick  chyba ($"
SES_ParamRequired       DB      ") Chìba povinnì parameter", 0dH, 0aH, "$"
SES_UnexpectedEOL       DB      ") NeoŸak vanì koniec riadka", 0dH, 0aH, "$"
SES_IllegalChar         DB      ") Neplatnì znak", 0dH, 0aH, "$"
SES_NameTooLong         DB      ") N zov ovl daŸa zariadenia je pr¡liç dlhì", 0dH, 0aH, "$"
SES_OpenBrExpected      DB      ") OŸak va sa (", 0dH, 0aH, "$"
SES_WrongHwName         DB      ") Nezn my n zov hardv‚rov‚ho zariadenia", 0dH, 0aH, "$"
SES_CommaExpected       DB      ") OŸak va sa ,", 0dH, 0aH, "$"
SES_CloseBrExpected     DB      ") OŸak va sa )", 0dH, 0aH, "$"
SES_WrongNumberPars     DB      ") Nespr vny poŸet parametrov", 0dH, 0aH, "$"
SES_TooManyPools        DB      ") Pr¡liç ve–a softv‚rovìch k¢dovìch str nok (MAX=5)", 0dH, 0aH, "$"
SES_ListTooLong         DB      ") Zoznam je pr¡liç dlhì", 0dH, 0aH, "$"
SES_TooManyHWPools      DB      ") Pr¡liç ve–a hardv‚rovìch k¢dovìch str nok", 0dh, 0ah, "$"
SES_NoAllocatedBufs     DB      ") Nedostatok pam„te na alok ciu vyrovn vacej pam„te", 0dH, 0aH, "$"
SES_InvalidParameter    DB      ") Neplatnì parameter", 0dh, 0ah, "$"

