# Language: Slovak (sk)
# File ending: sk
# Codepage: 852
INTRO=
ERROR.NOBINS=/fLightRed Nepodarilo sa n jsœ sieœov‚ ovl daŸe. /fGrey /p
ERROR.HARDWARE=/fLightRed Sieœovanie na fyzickom hardv‚ri nie je v s£Ÿasnosti podporovan‚. /fGrey /p
ERROR.DOSBOX=/fLightRed Sieœovanie v DOSBoxe nie je v s£Ÿasnosti podporovan‚. /fGrey /p
FOUND.QEMU=/fLightGreen Detegovan  sieœ QEMU. /fGrey /p
FOUND.VIRTUALBOX=/fLightGreen Detegovan  sieœ VirtualBOX. /fGrey /p
NOTES.VIRTUALBOX=/p /fLightGreen Vezmite pros¡m na vedomie, §e m“§e byœ potrebn‚ upraviœ nastavenia siete VirtualBOX. /fGrey /p
FOUND.VMWARE=/fLightGreen Detegovan  sieœ VMware. /fGrey /p
NOTES.VMWARE=/p /fLightGreen Vezmite pros¡m na vedomie, §e m“§e byœ potrebn‚ nakonfigurovaœ VMware pre re§im /fYellow Bridged /fLightGreen. /fGrey /p
FOUND.STAGING=/fLightGreen Detegovan  sieœ DOSBox Staging. /fGrey /p
NOTES.STAGING=/p /fLightGreen Vezmite pros¡m na vedomie, §e m“§e byœ potrebn‚ upraviœ nastavenia konfigur cie DOSBoxu. /fGrey /p
NO.NETWORK=/fLightRed 'Sieœ je nedostupn .' /fGray
USER.FDNETPD=/fLightGreen Pou§¡vaj£ sa vlastn‚ nastavenia paketov‚ho ovl daŸa v /fWhite FDNETPD.BAT /fGrey /p
USER.DRIVER=/fLightGreen Pou§¡va sa vlastnì paketovì ovl daŸ /fWhite %1 /fGrey /p
NO.HELP=Nepodarilo sa n jsœ s£bory pomocn¡ka.
NO.DRIVER=/fLightRed Nepodarilo sa n jsœ po§adovanì sieœovì ovl daŸ %1. /fGrey /p
