# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vfdutil [options]

N stroj pre s£bory a adres re.

    [none]      Nerob¡ niŸ.
    /D file     VypoŸ¡ta a vyp¡çe p¡smeno jednotky pre file na STDOUT.
    /P file     VypoŸ¡ta a vyp¡çe cestu pre file na STDOUT.
    /C          Pou§ite pred /D alebo /P na zmenu jednotky alebo cesty
                bez textov‚ho vìstupu.
    /X          Pou§ite pred /D alebo /P na vr tenie errorlevel 1-26
                pre p¡smeno jednotky.
    /F file     VypoŸ¡ta a vyp¡çe £plnì n zov s£boru na STDOUT.
    /B file     VypoŸ¡ta a vyp¡çe n zov s£boru s pr¡ponou na STDOUT.
    /N file     VypoŸ¡ta a vyp¡çe n zov s£boru bez pr¡pony na STDOUT.
    /E file     VypoŸ¡ta a vyp¡çe pr¡ponu s£boru na STDOUT.
    /U template VypoŸ¡ta a vyp¡çe jedineŸnì n zov s£boru/adres ra na
                z klade template na STDOUT. Jednotka a cesta musia
                existovaœ. Pr¡klad: "vfdutil /u C:\TEMP\TEST????.$$$"
    /S filespec H–ad  filespec v PATH a vyp¡çe vçetky zodpovedaj£ce
                s£bory na STDOUT. Aktu lny adres r sa nepreh–ad va. Ak
                sa filespec v ceste nen jde, skonŸ¡ s errorlevel 1.
    /T filespec Rovnak‚ ako /S, ale vr ti sa iba errorlevel.
    /M location Vyp¡çe mno§stvo vo–n‚ho miesta na disku pre location.
    /R required Pou§ite v spojen¡ s /M na otestovanie, Ÿi je k
                dispoz¡cii mno§stvo required miesta. Required je
                obmedzen‚ na 65535. D  sa k nemu ale pripojiœ B, K, M
                atÔ. Ak nie je dostatok miesta, vr ti errorlevel 1.
    /A path     Testuje, Ÿi v path existuj£ nejak‚ s£bory alebo adres re,
                0=adres r existuje a nie je pr zdnì, in‚ hodnoty s£
                chybov‚ k¢dy DOS z testu.

    tba         (St le vo vìvoji, Ôalçie bud£ ozn men‚)
