; Language: Slovak
; File ending: sk
; Codepage: 852
; This translation was made by Google Gemini.
; Please help the FreeDOS group to improve it.

; English Langauge Resource and Translation File
; changes by W. Spiegl: added %0 and %1 in line 84
; note %_ is a space, %% is percent, %r is CRLF,
; %0-F (1 char hex) are params, % alone is next param.
; Items that start VERB_ are Verbose mode versions.

LANGUAGE=sk
TITLE=%, Verzia %
COPYRIGHT=Autorsk‚ pr va (c) 2019-%, Jerome Shidel

; Same params as reporting
INC_FILE=%9%2 %8
INC_CONT=%2 (pokraŸovanie)
INC_DIR=%2
INC_TEXT=vlo§iœ text: %2 %8
INC_HEAD=text: %2 %8
USE_COMP=povolen  %0 pass-through kompresia

VERB_PRE_SCAN=naskenovanìch % polo§iek na pridanie do arch¡vu
VERB_INC_FILE=zahrn£œ: %9%2 (%A)\[%3] %8
VERB_INC_CONT=pokraŸovaœ: %2 [%3] (pokraŸuje od posunu %6)
VERB_INC_DIR=podadres r: %2 (%3)
VERB_INC_HEAD=vlo§iœ text hlaviŸky: %2 %8

; Excluded file or dir
VERB_EXCLUDE=vyl£Ÿiœ: %0 (zhoduje sa s "%1")

; Lists %0 is list, %1 is file
LIST_ITEM=%
LIST_FILE=pridaœ "%1" do %0 zoznamu
LIST_INC=zahrn£œ
LIST_EXC=vyl£Ÿiœ

; Same params as reporting
EXT_DIR=adres r: %2
EXT_FILE=s£bor: %9%2, %8
EXT_PART=ŸiastoŸnì: %9%2, %7 z %8
VERB_EXT_RPCL=s£bor %9%2 existuje, nahradenì
VERB_EXT_SKIP=s£bor %9%2 existuje, preskoŸenì

; Report & Extraction parameters
; %0 block ID    (all)
; %1 block size  (all)
; %2 name       (dir & file name, or text language)
; %3 unique ID (all)
; %4 attributes (dir & file attribs, or text verbose level)
; %5 time stamp (dir & file only)
; %6 file offest (file only)
; %7 file bytes (file only)
; %8 total file size (file and text only)
; %9 path (file only)
; %A path ID (file only)
REP_CAT=kateg¢ria: %2
REP_DIR=adres r: %2
REP_FILE=s£bor: %9%2, %8
REP_PART=ŸiastoŸnì: %9%2, %7 z %8
REP_TEXT=text: %2, %8
REP_MORE=pokraŸovanie: %2, %8
REP_CONF=prijaœ: %2, %8

VERB_REP_CAT=nastaviœ kateg¢riu: %2, %1
VERB_REP_DIR=adres r: %2 (%3), %1 %4 %5
VERB_REP_FILE=celì s£bor: %9%2 (%A)\[%3], %1
VERB_REP_FILE2=%4 %5 ve–kosœ s£boru %8
VERB_REP_PART=ŸiastoŸnì s£bor: %9%2 (%A)\[%3], %1
VERB_REP_PART2=%4 %5 %7 z %8 (posun %6)
VERB_REP_TEXT=text: %2 %4 {%3}, %8
VERB_REP_MORE=pokraŸovanie: %2 %4 {%3}, %8
VERB_REP_CONF=prijaœ: %2 %4 {%3}, %8
VERB_REP_SIG=podpis: %2 [%3], %1
VERB_REP_NULL=nulovì blok, %1
VERB_REP_OTHER=nezn my blok %0, %1
VERB_REP_SLICE=vybraœ Ÿasœ %

SAF_CREATE=Vytvoriœ novì slicer arch¡v %
SAF_OPEN=Otvoriœ existuj£ci slicer arch¡v %
SAF_APPEND=Pridaœ do existuj£ceho slicer arch¡vu %
SAF_DATE=Vytvoren‚ %2.%1.%0 o %3:%4:%5
SAF_SLICE=Vytvoriœ nov£ Ÿasœ arch¡vu %
SAF_CAT=Nastaviœ kateg¢riu arch¡vu %
SAF_SLICING=Rozdelenie arch¡vu na %
VERB_SAF_IUP=Aktualizovaœ çtatistick‚ inform cie pre arch¡v %

MEDIA=Vlo§te disketu so s£borom %0 do jednotky %1.
PAUSE=PokraŸujte stlaŸen¡m –ubovo–n‚ho kl vesu.

PROMPT_YES=µno
PROMPT_NO=Nie
PROMPT_Y=A
PROMPT_N=N
PROMPT_OVER=Prep¡saœ %2%1, %0?
PROMPT_ACCEPT=Prijaœ %?
PROMPT_STOP=S£bor %1 je poçkodenì. Preruçiœ rozba–ovanie %0?

SUMMARY=%0 Ÿasœ(¡), %1 adr., %2 s£bor(ov), %3

USAGE=pou§itie: % [mo§nosti]

; All help lines are displayed in order until the first missing number is
; encountered. You can add lines. But, keep the numbers in order by renumbering
; all lines after your additional help message. %0 is the Switch Character / or -
HELP_0=Inform cie o mo§nostiach SLICER:
HELP_1=
HELP_2=  %0q        zak zaœ vçetky stavov‚ spr vy
HELP_3=  %0v        povoliœ podrobn‚ stavov‚ spr vy
HELP_4=  %0t        testovac¡ re§im
HELP_5=  %0h        zobraziœ inform cie o pomocn¡kovi
HELP_6=
HELP_7=  %0i ?      zahrn£œ polo§ky zodpovedaj£ce çpecifik cii s£boru
HELP_8=  %0I ?      zahrn£œ polo§ky zo zoznamu s£borov
HELP_9=  %0e ?      vyl£Ÿiœ polo§ky zodpovedaj£ce çpecifik cii s£boru
HELP_10=  %0E ?      vyl£Ÿiœ polo§ky zo zoznamu s£borov
HELP_11=
HELP_12=  %0d        vyl£Ÿiœ pr zdne adres re
HELP_13=  %0D        neh–adaœ v podadres roch
HELP_14=  %0a        zahrn£œ vçetky skryt‚ a syst‚mov‚ polo§ky
HELP_15=  %0o        prep¡saœ existuj£ce s£bory
HELP_16=  %0k        neignorovaœ ve–k‚/mal‚ p¡smen  v n zvoch s£borov
HELP_17=
HELP_18=  %0g ?      zadaœ kateg¢riu skupiny
HELP_19=  %0s ?      ve–kosœ pre rozdelenie arch¡vu (K, M, bajty). (plat¡
HELP_20=             len pri vytv ran¡ nov‚ho alebo novom rozdelen¡)
HELP_21=
HELP_22=  %0y        automaticky prijaœ vçetky vìzvy (okrem prepisovania
HELP_23=             s£borov).
HELP_24=Oper cie tìkaj£ce sa cel‚ho arch¡vu:
HELP_25=
HELP_26=  %0f ?      zadaœ n zov s£boru arch¡vu
HELP_27=  %0c        vytvoriœ novì arch¡v
HELP_28=  %0r        pridaœ do existuj£ceho arch¡vu
HELP_29=  %0x        rozbaliœ z existuj£ceho arch¡vu
HELP_30=  %0R        vygenerovaœ spr vu o arch¡ve
HELP_31=  %0O ?      nastaviœ cie–ov£ cestu pre rozbalenie
HELP_32=
HELP_33=Vlo§enì text, upozornenia a spr vy:
HELP_34=
HELP_35=  %0L ?      prep¡saœ predvolenì jazyk syst‚mu
HELP_36=  %0m ?      vlo§iœ text spr vy zo s£boru
HELP_37=  %0M ?      vlo§iœ text zo s£boru, ktorì vy§aduje s£hlas pou§¡vate–a
HELP_38=
HELP_39=Pass-through kompresia:
HELP_40=
HELP_41=  %0p ?      povoliœ pass-through kompresiu (GZ, nesk“r mo§no in‚)
HELP_42=

; Reserved for future use
; HELP_00=  %0u        update existing archive
; HELP_00=  %0S        re-slice archive
; HELP_00=  %0w        write verification
; HELP_00=  %0z        use compression

NEEDHELP=Krajina zm„tku. Pre pomoc pou§ite vo–bu "%0h".

FATAL=KRITICKµ CHYBA:%_
ERROR=CHYBA:%_
BAD_OPT=Neplatnì parameter pr¡kazov‚ho riadka "%0%1"
BAD_CMB=Nemo§no kombinovaœ parametre "%0%1" a "%0%2"
BAD_MCO=Chìbaj£ce £daje pr¡kazov‚ho riadka pre "%0%1"
BAD_INT=Neplatn  Ÿ¡selna hodnota "%2" pre "%0%1"
BAD_VAL=¬¡selna hodnota "%2" je mimo rozsah "%3 - %4" pre "%0%1"
BAD_MAX=PrekroŸenì maxim lny poŸet Ÿast¡ arch¡vu pre "%1"
BAD_VER=Arch¡v "%1" m“§e obsahovaœ nepodporovan‚ d tov‚ çtrukt£ry.
BAD_EMB=S£Ÿasne je mo§n‚ zadaœ iba jeden textovì s£bor spr vy.
BAD_MSG=Pozn mka spr vy "%1" je pr¡liç ve–k . Skr ten‚ na %2.
BAD_CMP=Nepodporovan  pass-through kompresia "%2"
BAD_TMP=Vy§aduje sa adres r TEMP.
ER_UNK=k¢d chyby #%0, neçpecifikovan  chyba s "%1" %2
ER_2=S£bor "%1" nebol n jdenì.
ER_3=Cesta k s£boru "%1" nebola n jden .
ER_8=Hmm, nedostatok pam„te.
ER_11=S£bor "%1" m  nerozpoznanì form t.
ER_13=S£bor "%1" obsahuje poçkoden‚ £daje.
ER_14=Preruçen‚ pou§¡vate–om.
ER_23=Nezhoda podpisu. S£bor "%1" obsahuje poçkoden‚ £daje.

; Used for date time stamps
; DATE = %0 4 digit Year, %1 2 digit Month, %2 2 digit Day,
;        %3 2 digit year, %4 1-2 digit Month, %5 1-2 digit day
DATE=%2.%1.%0
; TIME = %0 Hour (24 hour), %1 Minute, %2 Second
;        %3 12 hour clock, %4 AM/PM
TIME=%0:%1:%2
AM=a
PM=p
; STAMP = %0 date, %1 time
STAMP=%0 o %1

BYTES=% bajt(ov)
KBYTES=% KiB
MBYTES=% MiB
FLOPPY=% disketa
