# Language: Slovak
# File ending: SK
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

.1 {Pam„œ: }
.2 {MB RAM}
.3 {Nainçtalovan‚ disky: }
.4 {vo–n‚}
.5 {Hl sen  verzia DOS: }
.6 {K¢dov  str nka a k¢d krajiny: }
.7 {Vo–n  konv. pam„œ: }
.8 {GB}
.9 {MB}
.10 {KB}
.11 {bajtov}
.12 {CPU novç¡ ako Pentium III}

.H {MYSYSINF (DOS implement cia linuxov‚ho n stroja NEOFETCH)}
.H {verzia 1.2}
.H {nap¡sal Laaca}
.H {Laaca@seznam.cz}
.H {}
.H {Parametre:}
.H {/? /H /I : tento pomocn¡k}
.H {}
.H {/G:1   : vyn£tiœ zobrazenie loga FreeDOS}
.H {/G:2   : vyn£tiœ zobrazenie vçeobecn‚ho loga DOS}
.H {}
.H {/L:<k¢d jazyka>}
.H {<k¢d jazyka> je s£bor s prelo§enìmi spr vami programu.}
.H {Pr¡klad: }
.H {MYSYSINF /L:cz    NaŸ¡ta s£bor MYSYSINF.CZ a prepne}
.H {                  spr vy programu do Ÿesk‚ho jazyka.}
.H {}
.H {This program is free software. You can redistribute and modify it under the}
.H {terms of the GNU GPL license.}
