# Language: Slovak (sk)
# File ending: sk
# Codepage: 852
# This translation was created by Google AI.
# Please help the FreeDOS group to improve it.

# Anglick‚ reœazce nap¡sal Ercan Ersoy.
0.0:  FDTUI je TUI Shell pre FreeDOS.
0.1:  Copyright (C) 2017-2022 Ercan Ersoy
0.2:  FDTUI je licencovanì pod GNU GPL verziou 2 a GNU GPL verziou 3.

1.0:Nepodarilo sa inicializovaœ subsyst‚m FDOSTUI.
1.1:\r\nStlaŸte –ubovo–nì kl ves pre n vrat do DOSSHELL.

2.0:Intern‚ aplik cie
2.1:Spr vca s£borov
2.2:Spustiœ

3.0:UkonŸiœ
3.1:Zavrieœ

4.0:Spr vca s£borov

5.0:S£bor
5.1:Otvoriœ
5.2:Novì adres r
5.3:UkonŸiœ

6.0:Upraviœ
6.1:Vystrihn£œ
6.2:Kop¡rovaœ
6.3:Vlo§iœ
6.4:Premenovaœ
6.5:Zmeniœ atrib£ty
6.6:Arch¡v
6.7:Skrytì
6.8:Iba na Ÿ¡tanie
6.9:Syst‚movì
6.10:Odstr niœ

7.0:Zobraziœ
7.1:Obnoviœ
7.2:Zobraziœ arch¡vne polo§ky
7.3:Zobraziœ skryt‚ polo§ky
7.4:Zobraziœ polo§ky iba na Ÿ¡tanie
7.5:Zobraziœ syst‚mov‚ polo§ky

8.0:Prejsœ
8.1:Sp„œ
8.2:Vpred
8.3:Hore

9.0:Novì adres r
9.1:N zov adres ra:

10.0:Premenovaœ
10.1:Novì n zov:

11.0:Atrib£ty polo§ky:

12.0:Spustiœ
12.1:Pr¡kaz na spustenie:
