# Language: Slovak (sk)
# File ending: sk
# Codepage: 852
# This translation was created by Google AI.
# Please help the FreeDOS group to improve it.

SHARE [/F:space] [/L:locks] [/U] [/S] [/O] [/D] [/E]
  /F:space   Vyhrad¡ miesto (v bajtoch) pre inform cie o zdie–an¡ s£borov.
  /L:locks   Nastav¡ poŸet s£borov, ktor‚ mo§no naraz uzamkn£œ.
  /U         Odinçtaluje rezidentn£ inçtanciu.
  /S         Zobraz¡ stav opr v a ve–kosti tabuliek.
  /O         Spustiœ iba ak je u§ rezidentnì, neinçtalovaœ.
  /D         Zak §e rezidentn£ inçtanciu.
  /E         Povol¡ rezidentn£ inçtanciu. (Predvolen‚.)

Inçtaluje funkcie zdie–ania s£borov a uzamykania na V ç pevnì disk.

