{
Language: Slovak
File ending: SK
Codepage: 852
This translation was made by Google Gemini.
Please help the FreeDOS group to improve it.

FDIMPLES Language Translation File

Note -- English translations are also built-in to the program. This file is not
required at runtime. However if it is present, settings in here will override
their built-in values.

}

0:SK
1:neplatnÏ parameter
2:Poükajte, pros°m...
3:¨akanie
4:Stlaüte kl†ves...
5:Skupina
6:MÇdium s bal°kmi sa nenaÁlo!
7:ZobrazenÇ s£ len nainÁtalovanÇ bal°ky.
8:nemoßno n†jsú spr†vcu bal°kov FDINST.
9:Premenn† prostredia TEMP nie je nastaven†.
10:nezn†my
11:nainÁtalovanÇ
12:¶iadne inform†cie
13:ZAMKNUTê
14:Bal°k
15:nen†jdenÏ v
16:NevybavenÇ zmeny bal°kov:
17:odstr†niú
18:nainÁtalovaú
19:¶iadne zmeny.

{ Plural String Values }
20:zmeny
21:zmena
22:bajty
23:bajt
24:Kbajty
25:Kbajt
26:Mbajty
27:Mbajt
28:s£bory
29:s£bor
30:zdrojovÇ s£bory
31:zdrojovÏ s£bor

{ Basic Load and save stuff }
32:Zahrn£ú odstr†nenia bal°kov.
33:Naü°taú £pravy zoznamu bal°kov:
34:Uloßiú £pravy zoznamu bal°kov:

{ Buttons }
35:OK
36:ZruÁiú

{ More Status Bar Text }
37:N†zov
38:verzia
39:poußitie:
40:[voñby]

{ Help Messages and such }
50:VydanÇ pod GNU General Public License, verzia 2.0
51:Copyright 2016-2024 Jerome Shidel
52:FDIMPLES poskytuje ñahko poußiteñnÇ textovÇ pouß°vateñskÇ rozhranie pre pr°kazovÏ n†stroj spr†vcu bal°kov FDINST.

53:Zobraziú t£to pomoc.
54:Zobraziú zoznam s£borov v popise bal°ka.
55:[NE]vyberaú automaticky aktualizovateñnÇ bal°ky.
56:Vytvoriú s£bory zoznamu bal°kov pre poußitie s n†strojom FDI build.
57:Prekonfigurovaú zoznamy bal°kov BASE a ALL inÁtal†tora FDI.

58:Kl†vesovÇ pr°kazy pouß°vateñskÇho rozhrania:
59:Prepn£ú vÏber.
60:Zmeniú akt°vnu sekciu alebo tlaüidlo.
61:Presun£ú fokus nahor alebo nadol, tieß Page Up/Down.
62:Ukonüiú bez vykonania alebo uloßenia zmien.
63:Zobraziú pomoc.
64:Prepn£ú stav vÁetkÏch aktualizovateñnÏch bal°kov v skupine.
65:Prepn£ú stav vÁetkÏch aktualizovateñnÏch bal°kov.
66:Zobraziú nevybavenÇ zmeny.
67:Vymazaú vÁetky nevybavenÇ zmeny.
68:Zap°saú s£bor £prav zoznamu bal°kov so zmenami.
69:Naü°taú s£bor £prav zoznamu bal°kov a aplikovaú zmeny.
70:Uspaú CPU pri neüinnosti.
71:Urüiú jednotku alebo cestu ako zdroj repozit†ra.

{ Package ID's Are all 100 }
100:=NainÁtalovanÇ!
100:BASE=FreeDOS Base
100:ARCHIVER=Archiv†tory
100:BOOT=Zav†dzacie n†stroje
100:DEVEL=VÏvoj
100:EDIT=Editory
100:EMULATOR=Emul†tory
100:GAMES=Hry
100:GUI=GrafickÇ plochy
100:NET=Sieú
100:SOUND=ZvukovÇ n†stroje
100:UNIXLIKE=N†stroje typu Unix
100:UTIL=Utility
100:UNIX=N†stroje typu Unix
100:OBSOLETE=ZastaranÇ bal°ky
100:APPS=Aplik†cie
100:DRIVERS=Ovl†daüe zariaden°
100:TOOLS=Z†kladnÇ n†stroje
100:DISK=DiskovÇ n†stroje
