# Language: Slovak (sk)
# File ending: sk
# Codepage: 852
# This translation was created by Google AI.
# Please help the FreeDOS group to improve it.

#
# Slovensk  vzorov  çabl¢na prekladu
#
0.0:Inçtaluje funkcie zdie–ania s£borov a uzamykania na v ç pevnì disk.\n
0.1:  /F:space   Vyhrad¡ miesto (v bajtoch) pre inform cie o zdie–an¡.\n
0.2:  /L:locks   Nastav¡ poŸet s£borov, ktor‚ mo§no naraz uzamkn£œ.\n
0.3:%s [/F:space] [/L:locks]\n
0.4:%s [/F:space] [/L:locks] [/U] [/S] [/O] [/D] [/E]\n
0.5:  /U         Odinçtaluje rezidentn£ inçtanciu.\n
0.6:  /S         Zobraz¡ stav opr v a ve–kosti tabuliek.\n
0.7:  /O         Spustiœ iba ak je u§ rezidentnì, neinçtalovaœ.\n
0.8:  /D         Zak §e rezidentn£ inçtanciu.\n
0.9:  /E         Povol¡ rezidentn£ inçtanciu. (Predvolen‚.)\n

1.0:%s: parameter mimo rozsahu!\n
1.1:%s: je u§ nainçtalovanì!\n
1.2:%s: nedostatok pam„te!\n
1.3:%s: neplatnì obslu§nì program preruçenia 2Fh!\n
1.4:%s: nainçtalovan‚.\n

1.5:%s: je u§ nainçtalovanì, ale nebol n jdenì na preruçen¡ AMIS!\n
1.6:%s: povolen‚.\n
1.7:%s: zak zan‚.\n
1.8:%s: nemo§no povoliœ, skontrolujte verziu TSR.\n
1.9:%s: nemo§no zak zaœ, skontrolujte verziu TSR.\n
1.10:%s: je nainçtalovanì ako rezidentnì.\n
1.11:%s: je nainçtalovanì ako rezidentnì, ale moment lne zak zanì.\n
1.12:%s: §iadne vo–n‚ multiplexn‚ Ÿ¡slo AMIS!\n
1.13:%s: neplatnì obslu§nì program preruçenia 2Dh!\n
1.14:%s: odstr nen‚.\n
1.15:%s: nemo§no odstr niœ, eçte nie je nainçtalovanì.\n
1.16:%s: nemo§no odstr niœ, doçlo k chybe.\n
1.17:%s: nemo§no odstr niœ, obsluhy s£ zah Ÿkovan‚ AMIS-nekompatibilne.\n
1.18:%s: nemo§no odstr niœ, intern  chyba pri odh Ÿkovan¡.\n
1.19:%s: nemo§no odstr niœ, nezn ma chyba.\n
1.20:%s: program nie je rezidentnì!\n

2.0:Program nie je rezidentnì!\n
2.1:Stav opravy: TSR nepodporuje.\n
2.2:Stav opravy: neurŸenì.\n
2.3:Stav opravy: potrebnì, pr¡znak na %04Xh:%04Xh.\n
2.4:Stav opravy: nie je potrebnì.\n
2.5:Stav opravy: nezn my.\n
2.6:Bajt share_installed star‚ho jadra FreeDOS vynulovanì.\n
2.7:Rezidentnì program vynuloval bajt share_installed star‚ho jadra FreeDOS.\n
2.8:Tabu–ka s£borov: %u vo–nìch / %u celkom, z mkov: %u vo–nìch / %u celkom\n
2.9:Tabu–ka s£borov: %u celkom, tabu–ka z mkov: %u celkom\n

