# Language: Slovak
# File ending: SK
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

FreeDOS NLSFUNC. Prid†va funkünosú NLS (National Language Support).
(C) 2004 Eduardo Casino, under the terms of the GNU GPL, Version 2

  NLSFUNC [/Y|/?] [[D:][PATH]SÈBOR]

  [D:][PATH]SÈBOR  Cesta k s£boru obsahuj£cemu NLS
  /Y               Naü°ta (voliteñn£) tabuñku µNO/NIE
  /?               Vyp°Áe poußitie

Pr°klad:

  CONFIG.SYS
     COUNTRY=34,858,C:\COUNTRY.SYS

  AUTOEXEC.BAT
     LH DISPLAY CON=(EGA,858,2)
     MODE CON CP PREP=((850) C:\CPI\EGA.CPI)
     MODE CON CP PREP=((,437) C:\CPI\EGA.CPI)
     LH NLSFUNC /Y

Potom prepnite k¢dovÇ str†nky pomocou pr°kazu CHCP systÇmu FreeCOM.

Ak nepotrebujete meniú k¢dovÇ str†nky, riadky MODE jednoducho vynechajte.
