# Language: slovakian
# File ending: sk
# Codepage: 852
# This translation was made by Google AI, please help
# the FreeDOS group to improve it.

0.0:µ
0.1:N
#### Miesto vyhraden‚ pre s£bor diskcopy.c ####
1.0:Neplatn  çpecifik cia jednotky alebo nevyberate–n‚ m‚dium.
1.1:Chyba pri Ÿ¡tan¡ konfiguraŸn‚ho s£boru.
1.2:Neplatnì prep¡naŸ:
1.3:Pr¡liç ve–a parametrov:
1.4:S£bor je chr nenì proti z pisu!
1.5:skop¡rovan‚ do
1.6:S£bor sa nenaçiel:
1.7:S£bor u§ existuje!
1.8:Vlo§te ZDROJOVé disketu do jednotky
1.9:PokraŸujte stlaŸen¡m –ubovo–n‚ho kl vesu . . .
1.10:Disk nie je pripravenì!
1.11:Nepodarilo sa otvoriœ s£bor obrazu.
1.12:Nedostatok miesta na cie–ovom disku!
1.13:Chyba pri pr¡stupe k s£boru obrazu:
1.14:Nedostatok pam„te pre kop¡rovanie disku.
1.15:Pou§itie
1.16:doŸasn‚ho s£boru.
1.17:¬¡tanie ZDROJOVEJ diskety . . .
1.18:Chyba m‚dia pri Ÿ¡tan¡ zo sektora
1.19:Z pis do s£boru obrazu.
1.20:NeoŸak van  chyba pam„te.
1.21:Vlo§te CIE•OVé disketu do jednotky
1.22:Disketa nem  rovnak£ kapacitu ako origin l.
1.23:Vlo§te disketu so spr vnou kapacitou do jednotky
1.24:alebo stlaŸte CTRL-C pre zruçenie.
1.25:Z pis na CIE•OVé disketu v jednotke . . .
1.26:¬¡tanie zo s£boru obrazu.
1.27:Chyba m‚dia pri z pise do sektora
1.28:Chcete Ôalçiu k¢piu tohto
1.29:s£boru obrazu (µ/N)?
1.30:disku (µ/N)?
1.31:Kop¡rovaœ Ôalç¡ disk (µ/N)?
1.32:Nemo§no skop¡rovaœ s£bor obrazu.
1.33:Probl‚m pri Ÿ¡tan¡ s£boru obrazu.
1.34:Vytv ranie s£boru obrazu . . .
1.35:Z pis s£boru obrazu . . .
1.36:Probl‚m pri z pise s£boru obrazu.
1.37:Chyba porovnania na sektore
1.38:Overovanie . . .
1.39:Pou§itie overenia
1.40:S‚riov‚ Ÿ¡slo zv„zku je
1.41:Sektor 0 je nezapisovate–nì! Chr nen‚ proti z pisu?
#### text je "Warning: options % doesn't do anything!" ####
2.0:Varovanie: vo–ba
2.1:niŸ nerob¡!
#### text je "Problem copying % to %" ####
3.0:Probl‚m pri kop¡rovan¡
3.1:do
#### text je "Copying % clusters, % sectors per cluster, ####
#### % bytes per sector.\n Drive size is % bytes" ####
4.0:Kop¡rovanie
4.1:clustrov
4.2:sektorov na cluster
4.3:bajtov na sektor.
4.4:Relevantn  ve–kosœ jednotky je
4.5:bajtov.
5.0:vyrovn vacia pam„œ o ve–kosti
5.1:bajtov.
#### Miesto vyhraden‚ pre s£bor parser.c ####
6.0:Syntaktick  chyba na riadku
6.1:v konfiguraŸnom s£bore
6.2:S‚mantick  chyba v konfiguraŸnom s£bore
6.3:nezad vajte viac ako jedno '='
6.4:Pros¡m zadajte YES alebo NO
6.5:Pros¡m zadajte NEVER alebo ALWAYS
6.6:pros¡m zadajte RECOVERY alebo NORMAL
6.7:pros¡m zadajte FAST alebo FULL
6.8:pros¡m zadajte UPDATE alebo LEAVE
#### Miesto vyhraden‚ pre s£bor recovery.c ####
6.10:Chyba m‚dia pri Ÿ¡tan¡, znova skenujem...
6.11:NeŸitate–nì sektor na poz¡cii
#### Miesto vyhraden‚ pre s£bor tdrvcpy.c ####
7.0:Vlo§te zdrojov£ disketu do jednotky
7.1:Vlo§te cie–ov£ disketu do jednotky
7.2:PokraŸujte stlaŸen¡m –ubovo–n‚ho kl vesu...
7.3:Neplatn  zdrojov  jednotka alebo nevyberate–n‚ m‚dium.
7.4:Neplatn  cie–ov  jednotka alebo nevyberate–n‚ m‚dium.
7.5:Disketa nem  rovnak£ kapacitu ako origin l.
7.6:Chyba: nedostatok pam„te.
7.7:Chyba m‚dia pri Ÿ¡tan¡ zo sektora
7.8:Chyba m‚dia pri z pise do sektora
7.9:Chcete skop¡rovaœ dve Ôalçie diskety ( /n)?
8.0:Vlo§te disketu so spr vnou kapacitou do jednotky
8.1:alebo
8.2:alebo stlaŸte CTRL-C pre zruçenie.
9.0:Kop¡rovanie
9.1:clustrov
9.2:sektorov na cluster
9.3:bajtov na sektor.
9.4:Relevantn  ve–kosœ jednotky je
9.5:bajtov.
9.6:Kop¡rovanie . . .
9.7:Overovanie . . .
#### Miesto vyhraden‚ pre reœazce pomocnej obrazovky ####
9.50:Skop¡ruje disketu alebo obraz na in£ disketu alebo obraz.
9.51:autor
9.52:zdroj
9.53:cie–
9.54:zdroj: jednotka alebo s£bor obrazu pre kop¡rovanie.
9.55:cie–: jednotka alebo s£bor obrazu pre z pis.
9.56:akustick‚ varovanie pri akcii pou§¡vate–a.
9.57:overovaœ Ÿ¡tanie a z pis.
9.58:pre kop¡rovanie pou§iœ iba pam„œ RAM.
9.59:zobraziœ vyu§itie pam„te (informat¡vne).
9.60:prep¡saœ cie–, ak u§ existuje (pri obrazoch).
9.61:v§dy automaticky ukonŸiœ.
9.62:predpokladaœ, §e disk je u§ v jednotke.
9.63:prejsœ do re§imu obnovy chìb disku.
9.64:vykonaœ rìchle kop¡rovanie (iba zaplnen‚ sektory).
9.65:Pozn mky: znamienko m¡nus za vo–bou ju zak §e.
9.66: Pre zdroj aj cie– m“§ete urŸiœ rovnak£ jednotku.
9.67:no-op pre kompatibilitu s MS-DOS.
9.40:nepìtaœ cie–ovì disk pri kop¡rovan¡ obrazu na ten istì disk.
