# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vchoice [options]

Vyberte vo–bu.

Vr ti errorlevel vybranej vo–by na z klade jej Ÿ¡sla polo§ky. Nie
p¡smena/Ÿ¡sla vo–by. Napr¡klad, ak je vybran  druh  polo§ka, vr ti
errorlevel 2. Bez oh–adu na predponu (ako C, 1, R atÔ.). Tie§ osobne
odpor£Ÿam pou§¡vaœ auto pre ak£ko–vek sadu volieb, ktor£ opatr¡te
predponou p¡smena alebo Ÿ¡sla.

    [none]      Vykonaœ so vçetkìmi automatickìmi predvolenìmi
                nastaveniami.
    /A n        Nastaviœ atrib£t textu na n pre vybran£ polo§ku.
    /B color    Nastaviœ farbu pozadia na color (alebo hodnotu)
                pre vybran£ polo§ku.
    /F color    Nastaviœ farbu popredia na color (alebo hodnotu)
                pre vybran£ polo§ku.
    /D n        Predvoliœ polo§ku Ÿ¡slo n ako predvolen£ vo–bu.
    type        Typ priameho vìberu kl vesom.
                    off     Vìber iba pomocou ç¡pok.
                    auto    Detegovaœ znaky priameho skoku. (Predvolen‚)
                    alpha   Skok na vo–by pomocou A-Z.
                    digit   Skok na vo–by pomocou 1-9 (+0).
    /Q          Dopyt na vìsledok. KeÔ je vo–ba vykonan , jej
                text bude odoslanì na STDOUT.
    /T seconds  Oneskorenie v sekund ch, kìm sa predvolen 
                polo§ka automaticky vyberie (0-3600). Upozoråujeme,
                §e aj keÔ pou§¡vate– prejde na in£ polo§ku, pri
                vyprçan¡ Ÿasov‚ho limitu sa vyberie p“vodn 
                predvolen  polo§ka.
    /P n        Pou§iœ re§im dopytovania a predvoliœ polo§ku n
                ako aktu lnu vo–bu. Pozn mka: ak ko–vek zmena
                vìberu ukonŸ¡ vchoice a vr ti 100+ Ÿ¡slo aktu lnej
                vo–by.
    /K n        Pou§iœ n namiesto znaku r mŸeka na detekciu
                hran¡c.
    CTRL-C      Ak je zadan‚ a stlaŸ¡te Control-C, program sa
                ukonŸ¡ s errorlevel 200.

    tba         (St le vo vìvoji, Ôalçie bud£ ozn men‚)
