# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vcls [options]

Vymaße obrazovku, oblasú alebo riadok (üiaru).

    [none]      Vymaße obrazovku s aktu†lnym atrib£tom textu.
    n           Nastav° atrib£t textu na n.
    /A n        Nastav° atrib£t textu na n.
    /B color    Nastav° atrib£t pozadia textu na color (alebo
                hodnotu).
    /F color    Nastav° atrib£t popredia textu na color (alebo
                hodnotu).
    /G          Glob†lne vymazanie obrazovky. (PredvolenÇ)
    /L          Lok†lne vymazanie obrazovky. Deteguje svoje
                okolie a vymaße iba to. Pravdepodobne r†müek,
                üiaru alebo tak nieüo. T£to moßnosú vlastne
                nepotrebujete. Pretoße r†müek moßno mìßete
                jednoducho prekresliú.
    /K n        Poußije n namiesto znakov r†müeka na detekciu
                okrajov.
    TEXT        Vymaße iba text. Ponech† vÁetky farby
                nedotknutÇ a ignoruje ich atrib£ty farieb.
    EOL         Vymaße iba od kurzora do konca riadka.
    /C code     Vymaße vyplnen°m k¢dom znaku ASCII.
    /X column   Absol£tny stípec obrazovky pre zaüiatok
                mazania.
    /Y row      Absol£tny riadok obrazovky pre zaüiatok
                mazania.
    /W width    Celkov† Á°rka oblasti na vymazanie.
    /H height   Celkov† vÏÁka oblasti na vymazanie.
