# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vdelete [vo–by]

Odstr ni riadok na aktu lnej poz¡cii.

    [§iadne]    Odstr niœ riadok.
    n           Odstr niœ n riadkov.
    /A n        Nastaviœ atrib£t textu na n.
    /B farba    Nastaviœ atrib£t pozadia textu na farbu (alebo hodnotu).
    /F farba    Nastaviœ atrib£t popredia textu na farbu (alebo hodnotu).
    /G          Glob lne odstr nenie.
    /L          Lok lne odstr nenie. (Predvolen‚)
    /K n        Pou§iœ n namiesto znaku r mu na detekciu hran¡c.
