# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vecho [options] [text]

Vyp°Áe text na obrazovku.

    [none]      Vykon† n†vrat voz°ka a posun riadka na obrazovke.
    text        Vyp°Áe text na obrazovku.
    /A n        Nastav° atrib£t textu na n.
    /B color    Nastav° atrib£t pozadia textu na color (alebo
                hodnotu).
    /F color    Nastav° atrib£t popredia textu na color (alebo
                hodnotu).
    /BlinkOn    Povol° bit blikania/intenzity. (Zaüne blikaú)
    /BlinkOff   Zak†ße bit blikania/intenzity. (Prestane blikaú)
    /N          Po dokonüen° nezap°Áe CRLF.
    /P          Teraz vykon† CRLF.
    /S +        Vloß° medzeru medzi parametre. (PREDVOLENê)
    /S -        Neprid† medzeru medzi viacerÏmi parametrami.
    /C code     Zap°Áe k¢d znaku ASCII.
    /R times    Opakuje ‘alÁ° z†pis times kr†t. (1-65535)
    /I          Vyp°Áe text, ktorÏ mìße üakaú zo zariadenia STDIN.
    /G          Vyp°Áe text glob†lne a ignoruje akÇkoñvek r†movanie.
    /L          Vyp°Áe text lok†lne s ohñadom na r†movanie.
                (PREDVOLENê)
    /K n        Poußije n namiesto znaku r†müeka na detekciu okrajov.
    /X code     Zmaße zvyÁok riadka pomocou k¢du ASCII, ale nepresunie
                kurzor.
    /E          RovnakÇ ako poußitie "/X 0x20" alebo "/X32".
    /T file ID  Vyhñad† ID v file a spracuje ho ako moßnosti
                pr°kazovÇho riadka. “alÁie moßnosti za tÏmto
                prep°naüom vyplnia premennÇ %1-%9 v textovom reúazci.

    tba         (St†le vo vÏvoji, ‘alÁie bud£ ozn†menÇ)
