# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vframe [options]

Vykresl¡ r mŸek typu okna a presunie kurzor do jeho –av‚ho horn‚ho rohu.

[none]          Vykresl¡ r mŸek obklopuj£ci cel£ obrazovku.
/A n            Nastaviœ atrib£t textu na n.
/B color        Nastaviœ atrib£t textu pozadia na color (alebo
                hodnotu).
/F color        Nastaviœ atrib£t textu popredia na color (alebo
                hodnotu).
/X column       St’pec obrazovky pre zaŸatie r mŸeka.
/Y row          Riadok obrazovky pre zaŸatie r mŸeka.
/W width        Celkov  ç¡rka r mŸeka.
/H height       Celkov  vìçka r mŸeka.
/C              Vycentruje r mŸek vodorovne a zvisle.
/T file ID      Vyh–ad  ID v file a spracuje ho ako
                parametre pr¡kazov‚ho riadka. Òalçie
                parametre po tomto prep¡naŸi vyplnia
                premenn‚ %1-%9 v texte.
/P n            Nastaviœ nevidite–nì znak vìplne n pre textbox
                a optionbox.
style           ætìly r mŸeka s£ Single, Double, SingleSides,
                DoubleSides a Hidden.
shadow          Pridaœ tieå v 3D çtìle.
textbox         Vykresl¡ r mŸek çtìlu textbox s trochou vìplne
                a okrajmi.
optionbox       Vykresl¡ skrytì çtìl optionbox pre vìbery
                vn£tri r mŸeka.
