# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vgotoxy [options]

Presunie alebo dopytuje poz°ciu kurzora.

[none]          Nevykon† ßiadnu akciu.
/Q x or y       Dopytuje aktu†lnu poz°ciu X alebo Y kurzora a
                vyp°Áe ju na STDOUT.
/X column       Presunie kurzor do stípca.
/Y row          Presunie kurzor do riadka.
/G              Presunie kurzor na z†klade celej obrazovky.
                (PredvolenÇ)
/L              Presunie kurzor na z†klade jeho okolia.
/K n            Poußiú n namiesto znaku r†müeka pre detekciu
                hran°c.
direction       Presunie kurzor hore, dole, vñavo alebo vpravo o
                jedno miesto.
shift           Presunie kurzor na predch†dzaj£cu alebo ‘alÁiu
                poz°ciu a zmen° riadky v pr°pade potreby.
position        Presunie kurzor na poz°ciu: SOP (Zaüiatok
                str†nky), EOP (Koniec str†nky), SOR (Zaüiatok
                riadka), EOR (Koniec riadka), SOL (Zaüiatok
                textu v riadku), EOL (Koniec textu v riadku),
                SOT (Zaüiatok celÇho textu) alebo EOT (Koniec
                celÇho textu).
