# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vinfo [options]
Vçeobecnì n stroj pre syst‚mov‚ inform cie.
    [none]      Nerob¡ niŸ.
    /V          Podrobnì re§im.
    /D a        Testuje stav jednotky.
                Vracia tieto errorlevel:
                   15 - Nie je k dispoz¡cii
                    5 - Nenaform tovan‚ (pre DOS)
                    4 - Sieœov  jednotka (netestovan‚)
                    3 - CD/DVD-ROM (Iba MSCDEX, v„Ÿçina vracia 15)
                    2 - Vymenite–n‚ m‚dium (napr. disketa)
                    1 - (Vyhraden‚)
                    0 - ¦iadne çpeci lne podmienky
    /M          Vr ti typ poŸ¡taŸa (m“§e zlyhaœ na bud£cich platform ch)
                Vracia tieto errorlevel:
                    0 - Nezn my, norm lny alebo nat¡vny 8086 hardv‚r.
                    1 - 80186
                    2 - 80286
                    3 - 80386
                    4 - 80486
                    5 - 80586
                    6 - 80686 alebo lepç¡
                  101 - DOSBox.
                  102 - QEMU.
                  103 - VirtualBox.
                  104 - VMware.
                  105 - Bochs.
    /P          Rovnak‚ ako /M, ale vynech  test pre virtu lne stroje.
    /T          Rovnak‚ ako /M, ale zahêåa vçeobecnì test emul tora.
                  200 - Vçeobecnì, detegovanì inì emul tor.
    /E n        Testuje fyzickì pevnì disk #n (1, 2 atÔ.) na stav MBR
                    0 - MBR je £plne pr zdny
                    5 - MBR obsahuje iba inform cie o oddieloch
                   10 - MBR obsahuje zav dzac¡ k¢d
                  101 - Vyskytla sa chyba
    /G          Grafika
                    0 - Nezn ma
                    1 - MDA
                    2 - HGC
                    3 - HGCPlus
                    4 - InColor
                    5 - CGA
                    6 - EGA
                    7 - MCGA
                    8 - VGA
                    9 - VESA/SuperVGA

Òalçie vo–by u§itoŸn‚ hlavne pre program torov a vìskum. S£ k dispoz¡cii
u§ dlho, ale ofici lne (odo måa) nie s£ s£Ÿasœou API V8Power Tools a m“§u
byœ kedyko–vek zmenen‚ alebo odstr nen‚. KeÔ§e ale niektor‚ pou§¡vam, mo§no
z nich vznikn£ samostatn‚ n stroje.
    ASCII       Zobraz¡ cel£ tabu–ku ASCII
    RAM         Vyp¡çe cel£ konvenŸn£ pam„œ na StdOut.
    /C * Vyp¡çe hodnoty ASCII pre zvyçok pr¡kazov‚ho riadka
    /R string   H–ad  string v celej konvenŸnej pam„ti
    /U string   H–ad  string v pam„ti (od a000:0000) bez oh–adu na ve–k‚ a
                mal‚ p¡smen 
    /J pos * Vr ti hodnotu ASCII znaku na poz¡cii pos vo zvyçku
                pr¡kazov‚ho riadka ako errorlevel. Vr ti 0, ak
                poz¡cia nebola n jden .
    /K pos * Rovnak‚ ako /J, ale najprv preveden‚ na ve–k‚ p¡smen .
    tba         (St le vo vìvoji, Ôalçie bud£ ozn men‚)
