# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vmath [options]

Jednoduchì matematickì n stroj. NIE JE to kalkulaŸka a priorita je
striktne z–ava doprava (to mo§no zmen¡m). Podporuje 64-bitov£
celoŸ¡seln£ matematiku na 8086 bez potreby koprocesora. V„Ÿçinou je to
dobr‚ pre sluŸky, urŸovanie posunov obrazovky atÔ.

+, ADD          PripoŸ¡taœ Ôalçie Ÿ¡slo k s£Ÿtu.
-, SUB          OdŸ¡taœ Ôalçie Ÿ¡slo od s£Ÿtu.
*, MUL          Vyn sobiœ s£Ÿet Ôalç¡m Ÿ¡slom.
/, DIV          Vydeliœ s£Ÿet Ôalç¡m Ÿ¡slom.
\, MOD          Vydeliœ s£Ÿet Ôalç¡m Ÿ¡slom a nastaviœ s£Ÿet na zvyçok.

AND             Logick‚ AND.
OR              Logick‚ OR.
XOR             Logick‚ XOR.
SHR             Bitovì posun vpravo.
SHL             Bitovì posun v–avo.

/H alebo /B     Nastaviœ vìstup na çestn stkovì alebo bin rny. Zatia–
                Ÿo vìpoŸty sa vykon vaj£ pomocou 64-bitovej matematiky,
                pri vìstupe v tìchto form toch sa vìsledky skracuj£ na
                najmençiu bitov£ ve–kosœ pre ich hodnotu. Napr¡klad
                na 64, 32, 16 alebo 8 bitov‚ Ÿ¡sla pod–a potreby.
