# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vmode [options]

Nastav¡ a zist¡ aktu lne textov‚ re§imy videa.

[none]      Vyp¡çe aktu lny re§im videa a p¡smo na STDOUT.
VESA        Vyp¡çe zoznam re§imov VESA na STDOUT.
mode        Nastav¡ aktu lny re§im videa. (0-0xffff) alebo
            çt¡tok re§imu s volite–nìm nastaven¡m p¡sma.

            Re§imy: BW40   ¬iernobiely 40 st’pcov (tie§ B40).
                    BW80   ¬iernobiely 80 st’pcov (tie§ B80, BW).
                    CO40   Farebnì 40 st’pcov (tie§ C40).
                    CO80   Farebnì 80 st’pcov (tie§ C80, COLOR).
                    MONO   Monochromatickì 80 st’pcov.

            P¡sma:  Font8  Vyberie p¡smo ROM 8x8. (tie§ F8)
                    Font14 Vyberie p¡smo ROM EGA 8x14. (tie§ F14)
                    Font16 Vyberie p¡smo ROM VGA 8x16. (tie§ F16)
