# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vpause [vo–by]

Jednoduch‚ Ÿakanie na stlaŸenie kl vesu alebo vyprçanie Ÿasu.

    [§iadne]    ¬akaœ donekoneŸna na stlaŸenie kl vesu.
    (/T)        Zastaran‚. Teraz /D.
    /D sekundy  Oneskorenie v sekund ch na Ÿakanie pred vyprçan¡m pauzy.
                (vracia errorlevel 1)
    CTRL-C      Ak je zadan‚ a stlaŸ¡ sa Control-C, ukonŸ¡ sa s
                errorlevel 200.

    tba         (St le vo vìvoji, Ôalçie bud£ ozn men‚)
