# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vpcspkr [hz:][ms]

Generovanie t¢nu pomocou vstavan‚ho reproduktora.

[none]          ¦iadny vìstup.
hz:ms           Pou§ite PC reproduktor na vygenerovanie t¢nu o
                frekvencii hz. Potom oneskorenie o ms milisek£nd.
                (Pozn mka: frekvencia 0 vypne reproduktor. Ak nie je
                zadan  §iadna frekvencia, predpoklad  sa 0)
/D              Detegovaœ met¢du pou§it£ pre Ÿasovanie.
                (Nekompatibiln‚ s VirtualBox)
/S              Pou§iœ bezpeŸnì ŸasovaŸ na vçeobecn‚ pou§itie.
                (Predvolen‚)
/I              Pou§iœ vysoko presnì ŸasovaŸ preruçenia.
                (Nekompatibiln‚ s VirtualBox)
tba             (St le vo vìvoji, Ôalçie bud£ ozn men‚)
