# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vprogres [options]

Vykresl¡ indik tor priebehu na aktu lnej poz¡cii bez presunu kurzora.

[none]          Vykresl¡ indik tor priebehu na 0%.
/A n            Nastav¡ atrib£t textu na n.
/B color        Nastav¡ atrib£t pozadia textu na color (alebo
                hodnotu).
/F color        Nastav¡ atrib£t popredia textu na color (alebo
                hodnotu).
/W width        Prep¡çe predvolen£ ç¡rku indik tora. (predvolen‚
                je od kurzora po koniec riadka)
/K n            Pou§ije n namiesto znaku r mŸeka na detekciu
                okrajov.
value           Nastav¡ hodnotu v percent ch priebehu.
off             Nezobrazuje percentu lne Ÿ¡slo.
align           Percentu lne Ÿ¡slo v–avo, uprostred (predvolen‚)
                alebo vpravo od indik tora priebehu.
OF max          VypoŸ¡ta percento z max. Pr¡klad 5 OF 7.
