# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vreadkey [options]

¬ak  na stlaŸenie kl vesu a vr ti jeho hodnotu ako çestn stkov‚ Ÿ¡slo
cez çtandardn‚ vìstupn‚ zariadenie, hodnota kl vesu bude vr ten  ako
%ERRORLEVEL%. Neplatn‚ prep¡naŸe alebo vo–by vr tia %ERRORLEVEL% 255.
æpeci lne kl vesy (ako ç¡pky) vr tia %ERRORLEVEL% nad 128.

/N              Nevypisovaœ hodnotu kl vesu na çtandardn‚ vìstupn‚
                zariadenie.
/D n            ¬asovì limit a vr ti predvolenì k¢d za n sek£nd
                (0-3600).
/R n            Nastaviœ predvolenì k¢d, ktorì sa vr ti pri vyprçan¡
                Ÿasu.
/P              Vymazaœ vstupn£ vyrovn vaciu pam„œ od Ÿakaj£cich
                stlaŸen¡ kl vesov.

tba             (St le vo vìvoji, Ôalçie bud£ ozn men‚)
