# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vver [vo–by]

InformaŸnì program V8Power.

    [§iadne]    Vyp¡çe vçetky inform cie do STDOUT.
    all         Vyp¡çe vçetky inform cie do STDOUT.
    title       Vyp¡çe plnì n zov do STDOUT.
    copyright   Vyp¡çe spr vu o autorskìch pr vach do STDOUT.
    version     Vyp¡çe inform cie o verzii do STDOUT.
    license     Vyp¡çe inform cie o licencii do STDOUT.
    url         Vyp¡çe inform cie o url webu do STDOUT.
    email       Vyp¡çe e-mailov£ adresu do STDOUT.
