# Language: Slovak
# File ending: SK
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

Inform cie o preklade jazyka pre EDICT

Pozn mka: Inform cie o premennìch s£ nieko–kìch typov a v çpecifickom porad¡,
ktor‚ sa (nateraz) ned  zmeniœ. Viacer‚ medzery sa automaticky skomprimuj£ do
jednej medzery, pokia– nie s£ v £vodzovk ch. Ak chcete zobraziœ £vodzovku, mus¡
byœ uveden  v inom type £vodzoviek. Nakoniec, pred ani za §iadnu premenn£ nie
s£ automaticky vkladan‚ §iadne medzery.

V ç prelo§enì jazykovì s£bor by mal byœ poskytnutì vo form te UTF-8 spolu s
verziou pre k¢dov£ str nku DOS, aby sa zabr nilo mo§nìm chyb m pri prevode
k¢dovìch str nok. Napr¡klad tureck‚ s£bory s£ EDICT.TR pre verziu DOS a
EDICT.TR.UTF-8 pre verziu UTF-8.

Òalçie inform cie o k¢doch jazykov a kraj¡n n jdete na adrese
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes.

Ako vìchodiskovì bod pre svoj preklad pou§ite jeden z existuj£cich prekladovìch
s£borov, napr¡klad EDICT.EN. Takto nebude chìbaœ §iadny potrebnì text.

Premenn‚:

    %_          Jeden znak medzery
    %%          Jeden symbol percenta
    %r          CRLF (koniec riadka)

    %c          Vlo§¡ premenn£ jedn‚ho znaku
    %s          Vlo§¡ premenn£ textov‚ho reœazca
    %b          Vlo§¡ premenn£ hexadecim lnej hodnoty bajtu
    %w          Vlo§¡ premenn£ hexadecim lnej hodnoty slova (nepou§it‚)
    %i          Vlo§¡ premenn£ cel‚ho Ÿ¡sla
    %I          Vlo§¡ premenn£ (cel‚ Ÿ¡slo + 1)


TITLE je n zov programu.
COPYRIGHT je moja spr va o autorskìch pr vach.

LANGUAGE nie je v predvolenom preklade a mal by byœ pravdepodobne v jazyku
prekladu. M“§ete uviesœ nieŸo ako jeden z tìchto:

LANGUAGE=Slovenskì preklad: [Meno]

HELP_* je text pre obrazovku n povedy. Ka§d  polo§ka sa zobrazuje na vlastnom
riadku. HneÔ ako program prvìkr t naraz¡ na chìbaj£cu polo§ku, vìstup n povedy
sa zastav¡. Podporovanìch je a§ 0xff (255).

INVALID sa pou§ije, ak je zadanì nerozpoznanì prep¡naŸ pr¡kazov‚ho riadka.

BAD_INT sa pou§ije, ak d“jde k chybe pri spracovan¡ Ÿ¡sla z pr¡kazov‚ho riadka.
BAD_VAL sa pou§ije, ak je Ÿ¡slo mimo rozsahu.

BErr_* s£ chybov‚ spr vy syst‚mu BIOS.
DErr_* s£ chybov‚ spr vy syst‚mu DOS.

S malou £pravou s£ texty chybovìch spr v BIOSu a DOSu v predvolenej externej
anglickej verzii zjednoduçenou verziou tìch, ktor‚ s£ dostupn‚ online z
vynikaj£ceho zdroja pre DOS a ASM na adrese:

    http://stanislavs.org/helppc/idx_interrupt.html

Aj keÔ je mo§n‚, §e ich Ÿasom vymen¡m za menej f dne vlastn‚ chybov‚ spr vy.

