# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vcursor [options]

Zmena alebo dotaz na ve–kosœ a tvar kurzora.

    [none]      Vyp¡çe aktu lny tvar kurzora na STDOUT.
    n           Nastav¡ aktu lny tvar kurzora na n.
    HIDE        Skryje kurzor.
    SMALL       Nastav¡ malì kurzor.
    HALF        Nastav¡ kurzor na 1/2 vìçky textu.
    FULL        Nastav¡ kurzor na pln£ vìçku textu.

Pozn mka: Hoci je tento n stroj plne kompatibilnì s DOSBox, neexistuje
sp“sob, ako ulo§iœ aktu lny tvar kurzora. Pozrite si pr¡klady, ako tento
probl‚m ob¡sœ. Tie§ tento n stroj nebude maœ §iadny £Ÿinok v termin li
Windows.
