# Language: Slovak
# File ending: SK
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

EDLIN 2.14

Program edlin je malì riadkovì editor, nap¡sanì pre FreeDOS ako funkŸnì klon
star‚ho programu edlin z MS-DOS. Od MS edlin sa l¡çi tìm, §e po prv‚ je to
slobodnì softv‚r a po druh‚, u§¡vate–sk‚ rozhranie je na nieko–kìch miestach
mierne odliçn‚. D“vodom rozdielu je, aby u§¡vate– nemusel zad vaœ riadiace
znaky vy§adovan‚ syntaxou MS edlin.

SPéæ›ANIE PROGRAMU EDLIN

Program edlin sa sp£çœa buÔ samostatne:

  edlin

alebo s n zvom s£boru, ktorì sa m  naŸ¡taœ pri çtarte:

  edlin s£bor

INTERN PRÖKAZY PROGRAMU EDLIN

V nasleduj£cich zoznamoch pr¡kazov predstavuj£ hranat‚ z tvorky volite–n‚
Ÿasti. Symbol # predstavuje Ÿ¡slo riadku, Ÿo je buÔ reœazec Ÿ¡slic, bodka (.)
predstavuj£ca aktu lny riadok, znak dol ra ($) predstavuj£ci poslednì riadok v
s£bore, alebo Ÿ¡slo riadku pripoŸ¡tan‚ alebo odpoŸ¡tan‚ od in‚ho Ÿ¡sla riadku,
tak§e

  .,.+1p

vyp¡çe aktu lny riadok a nasleduj£ci riadok.

Znak dol ra v nasleduj£cich zoznamoch predstavuje reœazec znakov. Tie m“§u byœ
uzavret‚ v jednoduchìch alebo dvojitìch £vodzovk ch a m“§u obsahovaœ
nasleduj£ce escape sekvencie:

  \a - vìstraha (p¡pnutie)
  \b - backspace (n vrat o znak)
  \e - escape
  \f - odriadkovanie str nky (formfeed)
  \t - horizont lny tabul tor
  \v - vertik lny tabul tor
  \" - dvojit  £vodzovka
  \' - jednoduch  £vodzovka
  \. - bodka
  \\ - sp„tn‚ lomka
  \xXX (kde X je hex Ÿ¡slica 0-9, a-f) - hexadecim lna konçtanta
  \dddd (kde d je dekadick  Ÿ¡slica 0-9) - decim lna konçtanta
  \OOO (kde O je okt lov  Ÿ¡slica 0-7) - okt lov  konçtanta
  \^C - riadiaci znak (control character)

Program edlin podporuje nasleduj£cu syntax:

# - éPRAVA JEDNHO RIADKU

Program edlin vyp¡çe jeden riadok urŸenì Ÿ¡slom a Ôalç¡ zadanì riadok nahrad¡
tento vyp¡sanì riadok v s£bore.

a - PRIPOJENIE (APPEND)

Tento pr¡kaz je ekvivalentnì k $+1i .

[#],[#],#,[#]c - KOPÖROVANIE ROZSAHU RIADKOV

Tento pr¡kaz skop¡ruje blok po sebe id£cich riadkov na in‚ miesto v pam„ti.
Parametre s£:

  * Prvì riadok, ktorì chcete kop¡rovaœ (predvolen‚ = aktu lny riadok)
  * Poslednì riadok, ktorì chcete kop¡rovaœ (predvolen‚ = aktu lny riadok)
  * Riadok, pred ktorì chcete vlo§iœ blok riadkov
  * PoŸet k¢pi¡ bloku (predvolen‚ = 1)

Po skop¡rovan¡ riadkov m“§ete pou§iœ pr¡kaz l (list) na zobrazenie spr vne
preŸ¡slovanìch riadkov.

[#][,#]d - VYMAZANIE BLOKU RIADKOV

Tento pr¡kaz vyma§e blok po sebe id£cich riadkov. Parametre s£ prvì a
poslednì riadok bloku, ktorì m  byœ vymazanì.

Ak vynech te druhì parameter, vyma§e sa iba riadok urŸenì prvìm parametrom.
Ak vynech te prvì parameter, vyma§e sa blok od aktu lneho riadku po riadok
urŸenì druhìm parametrom (nezabudnite uviesœ Ÿiarku). Vynechanie oboch
parametrov sp“sob¡ vymazanie aktu lneho riadku.

e s£bor - ULO¦I› A UKON¬I›

Tento pr¡kaz je ekvivalentnì s

  w s£bor

nasledovanìm

  q

[#]i - RE¦IM VKLADANIA

Tento pr¡kaz aktivuje re§im vkladania. Jeho parametrom je Ÿ¡slo riadku, pred
ktorì chcete vkladaœ riadky.

PoŸas vkladania s£ pr¡pustn‚ escape sekvencie uveden‚ vyççie. Re§im vkladania
ukonŸ¡te zadan¡m bodky (.) na samostatnom pr zdnom riadku (ak potrebujete
riadok obsahuj£ci iba bodku, pou§ite escape sekvenciu).

Po ukonŸen¡ re§imu vkladania sa riadok za vlo§enìm textom stane aktu lnym
riadkom, pokia– vkladanie nebolo vykonan‚ na koniec textu - v tom pr¡pade sa
novìm aktu lnym riadkom stane poslednì riadok textu.

[#][,#]l - VíPIS RIADKOV

Tento pr¡kaz vyp¡çe riadky textu na obrazovku. Ak vynech te prvì parameter,
pr¡kaz zaŸne zobrazovaœ text od 11 riadkov pred aktu lnym riadkom. Vynechanie
druh‚ho parametra zobraz¡ str nku textu zaŸ¡naj£cu riadkom urŸenìm v prvom
parametri. Vynechanie oboch parametrov zobraz¡ jednu str nku textu zaŸ¡naj£cu
11 riadkov pred aktu lnym riadkom. Ak je riadkov viac, ne§ sa zmest¡ na
str nku, program sa po ka§dej str nke zastav¡.

[#],[#],#m - PRESUN BLOKU

Tento pr¡kaz presunie blok textu pred riadok urŸenì v treœom parametri. Je to
podobn‚ kop¡rovaniu s n slednìm vymazan¡m p“vodn‚ho bloku.

[#][,#]p - STRµNKOVANIE (PAGE)

Podobn‚ ako l s tìm rozdielom, §e predvolen  str nka zaŸ¡na aktu lnym riadkom
namiesto 11 riadkov pred n¡m.

q - UKON¬I› (QUIT)

Zrozumite–n‚ samo o sebe. UkonŸ¡ bez Ôalçieho ukladania.

[#][,#][?]r$,$ - NAHRADI› RE›AZEC

Tento pr¡kaz nahrad¡ vçetky vìskyty prv‚ho reœazca druhìm reœazcom medzi
dvoma urŸenìmi riadkami. Vynechanì prvì parameter spust¡ nahradzovanie na
riadku za aktu lnym riadkom; vynechanì druhì parameter zastav¡ nahradzovanie
na poslednom riadku s£boru.

Ot znik (?) pred nahraden¡m odoçle potvrdzuj£cu spr vu.

[#][,#][?]s$ - H•ADA› PODRE›AZEC

Tento pr¡kaz h–ad  prvì riadok obsahuj£ci zadanì podreœazec. Vynechanie prv‚ho
parametra sp“sob¡ zah jenie h–adania na aktu lnom riadku; vynechanie druh‚ho
sp“sob¡ zastavenie h–adania na konci s£boru.

Ot znik (?) sp“sob¡, §e h–adanie odoçle potvrdzuj£cu spr vu. OdpoveÔ "N" (Nie)
v h–adan¡ pokraŸuje; odpoveÔ "A" (µno) ho ukonŸ¡.

Aktu lny riadok bude v pr¡pade £spechu nastavenì na riadok, kde h–adanie
skonŸilo.

[#]t s£bor - PRENIES› SéBOR

Tento pr¡kaz vlo§¡ obsah s£boru pred zadan‚ Ÿ¡slo riadku. Ak je Ÿ¡slo riadku
vynechan‚, predvolenou hodnotou je aktu lny riadok.

[#]w s£bor - ZAPÖSA› SéBOR

Tento pr¡kaz zap¡çe prvìch nieko–ko riadkov urŸenìch parametrom do zadan‚ho
s£boru. Ak je parameter vynechanì, zap¡çe do s£boru vçetky riadky v pam„ti.

AUTOR/SPRµVCA

Gregory Pietsch, gpietsch@comcast.net
