# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vdelay [ms]

Jednoduch‚ oneskorenie v milisekund ch.

    [§iadne]   Predvolen‚ je oneskorenie 1000ms (1 sekunda).
    ms         Oneskorenie o ms milisek£nd. (0-65535, 0x0000-0xffff)
    /D         Zistiœ met¢du pou§it£ na Ÿasovanie. (Nie je kompatibiln‚
               s VirtualBox)
    /S         Pou§iœ bezpeŸnì ŸasovaŸ pre vçeobecn‚ pou§itie. (Predvolen‚)
    /I         Pou§iœ vysoko presnì ŸasovaŸ preruçen¡. (Nie je kompatibiln‚
               s VirtualBox)
