# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was created by Google AI.
# Please help the FreeDOS group to improve it.

GNU Wget 1.11.1, neinterakt¡vny sieœovì sœahovaŸ.
Pou§itie: wget.exe [OPTION]... [URL]...

Povinn‚ argumenty pre dlh‚ vo–by s£ povinn‚ aj pre kr tke vo–by.

Spustenie:
  -V,  --version                    zobraz¡ verziu programu Wget a skonŸ¡.
  -h,  --help                       vyp¡çe t£to n povedu.
  -b,  --background                 po spusten¡ prejde do pozadia.
  -e,  --execute=COMMAND            vykon  pr¡kaz v çtìle `.wgetrc'.

Protokolovanie a vstupnì s£bor:
  -o,  --output-file=FILE           zapisuje spr vy do FILE.
  -a,  --append-output=FILE         pripoj¡ spr vy do FILE.
  -d,  --debug                      vypisuje ladiace inform cie.
       --wdebug                     vyp¡çe ladiaci vìstup Watt-32.
  -q,  --quiet                      tichì re§im (§iadny vìstup).
  -v,  --verbose                    podrobnì vìpis (predvolen‚).
  -nv, --no-verbose                 vypne podrobnì vìpis, bez tich‚ho
                                    re§imu.
  -i,  --input-file=FILE            stiahne URL n jden‚ v FILE.
  -F,  --force-html                 pova§uje vstupnì s£bor za HTML.
  -B,  --base=URL                   prid  URL pred relat¡vne odkazy v
                                    s£bore -F -i.

Sœahovanie:
  -t,  --tries=NUMBER               nastav¡ poŸet pokusov na NUMBER
                                    (0 neobmedzen‚).
       --retry-connrefused          sk£si to znova, aj keÔ je spojenie
                                    odmietnut‚.
  -O,  --output-document=FILE       zap¡çe dokumenty do FILE.
  -nc, --no-clobber                 preskoŸ¡ sœahovanie, ktor‚ by
                                    prep¡salo existuj£ce s£bory.
  -c,  --continue                   obnov¡ sœahovanie ŸiastoŸne
                                    stiahnut‚ho s£boru.
       --progress=TYPE              vyberie typ ukazovate–a priebehu.
  -N,  --timestamping               nesœahuje s£bory, pokia– nie s£
                                    novçie ako lok lne.
  -S,  --server-response            vyp¡çe odpoveÔ servera.
       --spider                     niŸ nesœahuje.
  -T,  --timeout=SECONDS            nastav¡ vçetky Ÿasov‚ limity na
                                    SECONDS.
       --dns-timeout=SECS           nastav¡ Ÿasovì limit DNS na SECS.
       --connect-timeout=SECS       nastav¡ Ÿasovì limit pripojenia
                                    na SECS.
       --read-timeout=SECS          nastav¡ Ÿasovì limit Ÿ¡tania na SECS.
  -w,  --wait=SECONDS               Ÿak  SECONDS medzi sœahovaniami.
       --waitretry=SECONDS          Ÿak  1..SECONDS medzi pokusmi.
       --random-wait                Ÿak  0...2*WAIT sek£nd medzi
                                    sœahovaniami.
       --no-proxy                   explicitne vypne proxy.
  -Q,  --quota=NUMBER               nastav¡ kv¢tu na sœahovanie na NUMBER.
       --bind-address=ADDRESS       zvia§e s ADDRESS (n zov/IP) lok lne.
       --limit-rate=RATE            obmedz¡ rìchlosœ sœahovania na RATE.
       --no-dns-cache               zak §e vyrovn vaciu pam„œ DNS dotazov.
       --restrict-file-names=OS     obmedz¡ znaky v n zvoch s£borov
                                    pre OS.
       --ignore-case                ignoruje ve–kosœ p¡smen pri h–adan¡.
  -4,  --inet4-only                 prip ja sa iba k IPv4 adres m.
  -6,  --inet6-only                 prip ja sa iba k IPv6 adres m.
       --prefer-family=FAMILY       pripoj¡ sa najprv k tejto rodine,
                                    jednej z IPv6, IPv4 alebo none.
       --user=USER                  nastav¡ pou§¡vate–a FTP a HTTP na
                                    USER.
       --password=PASS              nastav¡ heslo FTP a HTTP na PASS.

Adres re:
  -nd, --no-directories             nevytv ra adres re.
  -x,  --force-directories          vyn£ti vytvorenie adres rov.
  -nH, --no-host-directories        nevytv ra adres re hostite–a.
       --protocol-directories       pou§ije n zov protokolu v adres roch.
  -P,  --directory-prefix=PREFIX    ulo§¡ s£bory do PREFIX/...
       --cut-dirs=NUMBER            ignoruje NUMBER komponentov
                                    vzdialen‚ho adres ra.

Volby HTTP:
       --http-user=USER             nastav¡ pou§¡vate–a HTTP na USER.
       --http-password=PASS         nastav¡ heslo HTTP na PASS.
       --no-cache                   zak §e d ta z vyrovn vacej pam„te
                                    servera.
  -E,  --html-extension             ulo§¡ HTML dokumenty s pr¡ponou
                                    `.html'.
       --ignore-length              ignoruje pole hlaviŸky
                                    `Content-Length'.
       --header=STRING              vlo§¡ STRING medzi hlaviŸky.
       --max-redirect               maxim lny poŸet presmerovan¡ na
                                    str nku.
       --proxy-user=USER            nastav¡ USER ako pou§¡vate–sk‚ meno
                                    proxy.
       --proxy-password=PASS        nastav¡ PASS ako heslo proxy.
       --referer=URL                vlo§¡ hlaviŸku `Referer: URL' do
                                    po§iadavky.
       --save-headers               ulo§¡ HTTP hlaviŸky do s£boru.
  -U,  --user-agent=AGENT           identifikuje sa ako AGENT namiesto
                                    Wget.
       --no-http-keep-alive         zak §e HTTP keep-alive.
       --no-cookies                 nepou§¡va cookies.
       --load-cookies=FILE          naŸ¡ta cookies z FILE pred rel ciou.
       --save-cookies=FILE          ulo§¡ cookies do FILE po rel cii.
       --keep-session-cookies       naŸ¡ta a ulo§¡ relaŸn‚ cookies.
       --post-data=STRING           pou§ije met¢du POST; odoçle STRING.
       --post-file=FILE             pou§ije met¢du POST; odoçle obsah
                                    FILE.
       --content-disposition        reçpektuje hlaviŸku
                                    Content-Disposition pri vìbere
                                    lok lnych n zvov (EXPERIMENTµLNE).
       --auth-no-challenge          Odoçle z kladn£ HTTP autentifik ciu
                                    bez Ÿakania na vìzvu servera.

Volby HTTPS (SSL/TLS):
       --secure-protocol=PR         vyberie bezpeŸnì protokol, jeden z
                                    auto, SSLv2, SSLv3 a TLSv1.
       --no-check-certificate       neoveruje certifik t servera.
       --certificate=FILE           s£bor klientskeho certifik tu.
       --certificate-type=TYPE      typ klientskeho certifik tu, PEM
                                    alebo DER.
       --private-key=FILE           s£bor s£kromn‚ho k–£Ÿa.
       --private-key-type=TYPE      typ s£kromn‚ho k–£Ÿa, PEM alebo DER.
       --ca-certificate=FILE        s£bor so sadou certifikaŸnìch
                                    autor¡t.
       --ca-directory=DIR           adres r s hash zoznamom CA.
       --random-file=FILE           s£bor s n hodnìmi d tami pre SSL
                                    PRNG.
       --egd-file=FILE              s£bor oznaŸuj£ci EGD soket.

Volby FTP:
       --ftp-user=USER              nastav¡ pou§¡vate–a FTP na USER.
       --ftp-password=PASS          nastav¡ heslo FTP na PASS.
       --no-remove-listing          neodstr ni s£bory `.listing'.
       --no-glob                    vypne doplåovanie n zvov s£borov FTP.
       --no-passive-ftp             vypne "pas¡vny" re§im prenosu.
       --retr-symlinks              pri rekurzii sœahuje odkazovan‚
                                    s£bory.
       --preserve-permissions       zachov  opr vnenia vzdialen‚ho
                                    s£boru.

Rekurz¡vne sœahovanie:
  -r,  --recursive                  zapne rekurz¡vne sœahovanie.
  -l,  --level=NUMBER               maxim lna h’bka rekurzie (inf/0 pre
                                    nekoneŸno).
       --delete-after               zma§e s£bory lok lne po stiahnut¡.
  -k,  --convert-links              konvertuje odkazy v HTML na lok lne.
  -K,  --backup-converted           pred konverziou s£boru X vytvor¡
                                    z lohu ako X.orig.
  -m,  --mirror                     skratka pre -N -r -l inf
                                    --no-remove-listing.
  -p,  --page-requisites            stiahne vçetky obr zky atÔ. pre
                                    HTML.
       --strict-comments            zapne striktn‚ (SGML) spracovanie
                                    HTML koment rov.

Rekurz¡vne prijatie/odmietnutie:
  -A,  --accept=LIST                Ÿiarkou oddelenì zoznam prijatìch
                                    pr¡pon.
  -R,  --reject=LIST                Ÿiarkou oddelenì zoznam odmietnutìch
                                    pr¡pon.
  -D,  --domains=LIST               Ÿiarkou oddelenì zoznam prijatìch
                                    dom‚n.
       --exclude-domains=LIST       Ÿiarkou oddelenì zoznam odmietnutìch
                                    dom‚n.
       --follow-ftp                 nasleduje FTP odkazy z HTML
                                    dokumentov.
       --follow-tags=LIST           Ÿiarkou oddelenì zoznam sledovanìch
                                    HTML tagov.
       --ignore-tags=LIST           Ÿiarkou oddelenì zoznam ignorovanìch
                                    HTML tagov.
  -H,  --span-hosts                 pri rekurzii prech dza na cudzie
                                    hostitele.
  -L,  --relative                   nasleduje iba relat¡vne odkazy.
  -I,  --include-directories=LIST   zoznam povolenìch adres rov.
  -X,  --exclude-directories=LIST   zoznam vyl£Ÿenìch adres rov.
  -np, --no-parent                  neprech dza do nadraden‚ho adres ra.

Chyby a n vrhy posielajte na <bug-wget@gnu.org>.
