# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vfont [vo–by]
DoŸasne naŸ¡taœ bitmapov‚ p¡smo textov‚ho re§imu.

    s£bor       NaŸ¡taœ s£bor p¡sma.
    /F n s£bor  Ak m  aktu lne p¡smo n (Ÿ¡slo, EGA alebo VGA) riadkov,
                naŸ¡taœ s£bor p¡sma. Mo§no reœaziœ pre r“zne rozl¡çenia.
    /D          NaŸ¡taœ predvolen‚ p¡smo pre aktu lne rozl¡çenie.

    tba         (St le vo vìvoji, Ôalçie bud£ ozn men‚)
