# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vinsert [vo–by]

Vlo§¡ pr zdny riadok na aktu lnej poz¡cii.

    [§iadne]    Vlo§iœ pr zdny riadok.
    n           Vlo§iœ n pr zdnych riadkov.
    /A n        Nastaviœ atrib£t textu na n.
    /B farba    Nastaviœ atrib£t pozadia textu na farbu (alebo hodnotu).
    /F farba    Nastaviœ atrib£t popredia textu na farbu (alebo hodnotu).
    /G          Glob lne vlo§enie.
    /L          Lok lne vlo§enie. (Predvolen‚)
    /K n        Pou§iœ n namiesto znaku r mu na detekciu hran¡c.
