# bp Brazilian Portuguese, bp, cp850/858
# Translation made by Google Gemini
# This translation was made by Google AI, please help the FreeDOS group
# to improve it.

carregado, consumindo %u bytes.
carregado na mem¢ria alta, consumindo %u bytes.
\nN∆o foi poss°vel encontrar/abrir o arquivo de tabela Unicode %s!
\nConte£do incorreto no arquivo %s ou erro de leitura!
desativado.
\n(Outro TSR capturou Int21 e/ou Int2F)
Ainda n∆o instalado!
requer pelo menos a vers∆o 4 do DOS!
opá∆o(‰es) aceita(s)
"
++ FREEWARE ++
Programa que suporta nomes longos de arquivos em puro DOS.
USE ESTE PROGRAMA POR SUA CONTA E RISCO, PODE HAVER PERDA DE DADOS
Aá‰es: - (nada) carregar e/ou ativar TSR
- h ou ? esta ajuda
- d desativar DOSLFN
- s mostrar status e configuraá‰es
?PROFILE
- p mostrar dados de perfil
- pr resetar dados de perfil
- pc calibrar tempo de perfil
?
- u descarregar TSR da mem¢ria
Opá‰es: - w{+|-} * acesso de escrita
- ~{+|-} * uso de til (nome numÇrico curto)
- t{+|-} * efeito t£nel (preservaá∆o de nomes)
- f{+|-} * modo fallback - LFN para todos os drives
- c{+|-} * suporte a CDROM
- i{+|-} * trava de reentrada via flag InDOS + RESET DRIVE
- r{+|-} * bit de somente leitura para arquivos CD
?USEWINTIME
- o[N] * definir fuso hor†rio N ou ler TZ se ausente
?
- z[:|=]tabela carregar tabela Unicode (.TBL)
- m[:|=]bytes tamanho do heap interno, 600..50000
- ms[:|=]bytes tamanho do caminho curto, 16..141
- ml[:|=]bytes tamanho do caminho longo, 16..1024
- mn[:|=]bytes tamanho do nome longo, 13..512
- p[:|=]path diret¢rio de trabalho para .TBL/.386
Ambiente: LANG=cc idioma das mensagens (NLS\DOSLFN.cc)
?USEWINTIME
TZ=xxxNyyy fuso hor†rio N para convers∆o, sem DST
?
Email: %s
Download: %s
%s
"
ativo
ativado.
removido da mem¢ria.
%7lu acessos de leitura
%7lu acessos de escrita
%7lu chamadas Int21/AH=71
acesso de escrita
uso de til
efeito t£nel
suporte a CDROM
modo fallback
bit somente-leitura em arquivos CD
tamanho de heap inv†lido
LIG
DESL
%35s %s\n
diret¢rio n∆o existe!
n∆o pìde definir diret¢rio de trabalho
n∆o pìde redimensionar heap
opá∆o rejeitada

    descarregue o TSR primeiro.
    \nEste programa Ç in£til em uma janela DOS desta vers∆o do Windows!
    Heap: tam=%u, usado=%u, livre=%u, m†x-disp=%u Bytes\n
    Uso de flag InDOS e RESET drive
    Èltimo erro: %u -\s
    o usu†rio negou acesso de escrita
    n∆o pìde expandir diret¢rio FAT
    mem¢ria insuficiente - aumente o heap
    n∆o pìde carregar a tabela Unicode automaticamente
    ?USEWINTIME
    Fuso hor†rio Ç
    %35s UTC%+d\n
    ?
    ?PROFILE
    Perfil.\n
    Perfil resetado.\n
    %7lu %2d.%03d %s\n
    Calibrando perfil.\n
    Constante de tempo do perfil = %lu000\n
    Erro ao executar calibraá∆o\n
    ?

