# Language: Slovak
# File ending: sk
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

vview [options] file

Prehliadaü s£borov. Podporuje s£bory do 2GB pouß°vaj£ce ukonüenie
riadkov CRLF, CR alebo LF. Na rozdiel od vÑüÁiny n†strojov V8Power
t†to utilita predvolene pouß°va cel£ obrazovku. Pre poußitie VVIEW
vn£tri r†müeka VFRAME mus°te zadaú miestny reßim zobrazenia.

/A n            Nastaviú atrib£t textu na n.
/B color        Nastaviú atrib£t textu pozadia na color.
/F color        Nastaviú atrib£t textu popredia na color.
/G              Poußiú cel£ obrazovku. (PredvolenÇ)
/L              Miestne zobrazenie vn£tri VFRAME. Deteguje svoje
                okolie a pouß°va iba üasú obrazovky.
                Pravdepodobne r†müek, üiaru alebo podobnÇ.
/K n            Poußiú n namiesto znakov r†müeka pre detekciu
                hran°c.

Poüas prehliadania s£boru mìßete pouß°vaú kl†vesy Up, Down, Left,
Right, PgUp, PgDn, Home a End pre navig†ciu. Pre ukonüenie
prehliadania stlaüte kl†vesu Escape. Ak bolo zadanÏch viacero
s£borov, bud£ sa prehliadaú jeden po druhom.

tba             (St†le vo vÏvoji, viac bude ozn†menÇ neskìr)
