# Language: slovak / slowakisch
# File ending: sk
# Codepage: 852
# Translation made by Google Gemini
# This translation was made by Google AI, please help the FreeDOS group
# to improve it.
99.0:Vytlaü° lokalizovan£ spr†vu (z localize.)
99.1:Vytlaü° spr†vu ü°slo x.y alebo, ak nie je k dispoz°cii, text za @@@\r\n(a nakoniec zopakuje [at‘.], ak nejakÇ je)
99.2:Errorlevel: 0, ak je v poriadku, 1, ak nebolo n†jdenÇ ßiadne localize. alebo ßiadna spr†va x.y vo vn£tri.
