# Language: Slovak
# File ending: SK
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

$OS_NAME$ je otvorenì operaŸnì syst‚m kompatibilnì s DOS-om, ktorì m“§ete
pou§iœ na hranie klasickìch hier pre DOS, sp£çœanie starçieho podnikov‚ho
softv‚ru alebo vìvoj vstavanìch syst‚mov. Ka§dì program, ktorì funguje v
syst‚me MS-DOS, by mal be§aœ aj v syst‚me $OS_NAME$.
*

V syst‚me $OS_NAME$ m“§ete hraœ svoje ob–£ben‚ hry pre DOS. A na hranie je
tu mno§stvo skvelìch klasickìch hier: Wolfenstein 3D, Doom, Commander Keen,
Rise of the Triad, Jill of the Jungle, Duke Nukem a mnoho Ôalç¡ch!
*

Potrebujete obnoviœ £daje zo star‚ho podnikov‚ho programu? Alebo mo§no
potrebujete spustiœ zostavu zo svojho star‚ho finanŸn‚ho syst‚mu? StaŸ¡
nainçtalovaœ v ç starç¡ softv‚r pod $OS_NAME$ a m“§ete zaŸaœ!
*

Mnoho vstavanìch syst‚mov be§¡ na DOS-e, hoci modern‚ syst‚my m“§u namiesto
toho vyu§¡vaœ Linux. Ak spravujete starç¡ vstavanì syst‚m, mo§no pou§¡vate
DOS. A $OS_NAME$ sa pre tento £Ÿel ve–mi dobre hod¡.
*

$OS_NAME$ je softv‚r s otvorenìm zdrojovìm k¢dom!
Stiahnutie a pou§¡vanie $OS_NAME$ niŸ nestoj¡.
*

FreeDOS Alpha 1 bol vydanì 16. septembra 1994. To je viac ako 30 rokov hist¢rie.
*

$OS_NAME$ m“§ete tie§ zdie–aœ s ostatnìmi! A m“§ete si prezeraœ a upravovaœ
n ç zdrojovì k¢d, preto§e vçetky programy $OS_NAME$ s£ ç¡ren‚ pod licenciou
GNU General Public License alebo podobnou licenciou pre otvorenì softv‚r.
*

$OS_NAME$ bol v§dy o vìvoj roch, ktor¡ sa spojili, aby p¡sali k¢d. Navçt¡vte
webov£ str nku projektu $OS_NAME$, kde n jdete viac inform ci¡ o tom, ako
m“§ete prispieœ do $OS_NAME$.
*

M te ot zky tìkaj£ce sa nastavenia alebo pou§¡vania $OS_NAME$? Pozrite
si e-mailov£ konferenciu FreeDOS-user na str nke F¢rum na webovej str nke.
