# Language: slovakian
# File ending: sk
# Codepage: 852
# Translation made by Google Gemini
# This translation was made by Google AI, please help the 
# FreeDOS group to improve it.

FreeDOS APPEND. Umo§åuje programom otv raœ d tov‚ s£bory v zadanìch
adres roch, akoby boli v aktu lnom adres ri.
(C) 2004-2006 Eduardo Casino, pod podmienkami GNU GPL, verzia 2

Syntax:

APPEND [[jednotka:]cesta[;...]] [/X[:ON|:OFF]] [/PATH:ON|/PATH:OFF] [/E]
APPEND ;

[jednotka:]cesta Jednotka a adres r na pripojenie.
/X[:ON]          Rozç¡ri APPEND na vyh–ad vanie a sp£çœanie pr¡kazov.
/X:OFF           APPEND sa pou§ije len pri otv ran¡ s£borov.
                 Predvolen‚ je /X:OFF.
/PATH:ON         H–ad  v pripojenìch adres roch po§adavky, ktor‚ u§
                 obsahuj£ cestu. Toto je predvolen‚ nastavenie.
/PATH:OFF        Vypne vo–bu /PATH:ON.
/E               Ulo§¡ zoznam pripojenìch adres rov do prostredia.
                 /E sa smie pou§iœ len pri prvom volan¡ APPEND.
                 Na tej istej pr¡kazovej riadke s /E nesm£ byœ cesty.

APPEND ; vyma§e zoznam pripojenìch adres rov.
APPEND bez parametrov zobraz¡ zoznam pripojenìch adres rov.

Pozn mka:

APPEND sa po prvom spusten¡ nainçtaluje ako internì pr¡kaz.
Druh‚ a Ôalçie volania MUSIA byœ bez cesty k s£boru a pr¡pony.
