# language: Polish (Polski, pl)
# codepage: CP852
# translators: Gemini
# To jest tekst wygenerowany automatycznie. Jeòli znajdziesz bà©dy,
# popraw je i poinformuj grup© FreeDOS.

zaàadowany, zajmuje %u bajt¢w.
zaàadowany do pami©ci g¢rnej, zajmuje %u bajt¢w.
\nNie moæna znale´Ü/otworzyÜ pliku tablicy Unicode %s!
\nPlik %s: zàa zawartoòÜ lub nie moæna odczytaÜ!
wyà•czony.
\n(Inny program TSR przej•à Int21 i/lub Int2F)
Jeszcze nie zainstalowany!
wymaga co najmniej DOS w wersji 4!
przeà•cznik(i) przyj©ty
"
++ FREEWARE ++
Program obsàuguj•cy dàugie nazwy plik¢w w czystym DOS.
UΩYWAJ TEGO PROGRAMU NA WùASNE RYZYKO, MOΩLIWA UTRATA DANYCH
Dziaàania:    - (nic)	       zaàaduj i/lub wà•cz TSR
	      - h lub ?        ta pomoc
	      - d	       wyà•cz DOSLFN
	      - s	       pokaæ status i ustawienia
?PROFILE
	      - p	       pokaæ dane profilu
	      - pr	       zresetuj dane profilu
	      - pc	       kalibruj czas profilu
?
	      - u	       usu‰ TSR
Przeà•czniki: - w{+|-}	       * dost©p do zapisu
	      - ~{+|-}	       * uæycie tyldy (NameNumericTail)
	      - t{+|-}	       * efekt tunelu (Zachowaj Nazwy)
	      - f{+|-}	       * tryb awaryjny: LFN dla wszystkich nap©d¢w
	      - c{+|-}	       * obsàuga CD-ROM
	      - i{+|-}	       * blokada ponownego wejòcia (InDOS/RESET)
	      - r{+|-}	       * bit tylko do odczytu dla plik¢w CD
?USEWINTIME
	      - o[N]	       * ustaw stref© czasow• N lub czytaj TZ
?
	      - z[:|=]tabela   zaàaduj tablic© Unicode (.TBL)
	      - m[:|=]bajty    deklaruj rozmiar sterty, 600..50000
	      - ms[:|=]bajty   deklaruj rozm. kr¢tkiej òcieæki, 16..141
	      - ml[:|=]bajty   deklaruj rozm. dàugiej òcieæki, 16..1024
	      - mn[:|=]bajty   deklaruj rozm. dàugiej nazwy, 13..512
	      - p[:|=]òcieæka  deklaruj katalog roboczy dla .TBL/.386
Zmienne:      LANG=cc	       j©zyk komunikat¢w (NLS\DOSLFN.cc)
?USEWINTIME
	      TZ=xxxNyyy       strefa czasowa N, bez czasu letniego
?
Email:	  %s
Download: %s
	  %s
"
aktywny
wà•czony.
usuni©ty z pami©ci.
%7lu odczyt¢w
%7lu zapis¢w
%7lu wywoàa‰ Int21/AH=71
dost©p do zapisu
uæycie tyldy
efekt tunelu
obsàuga CD-ROM
tryb awaryjny
bit tylko do odczytu na plikach CD
nieprawidàowy rozmiar sterty
ON
OFF
%37s %s\n
katalog nie istnieje!
nie moæna ustawiÜ katalogu roboczego
nie moæna zmieniÜ rozmiaru sterty
przeà•cznik odrzucony
 - najpierw usu‰ TSR.
\nTen program jest bezuæyteczny w oknie DOS tej wersji Windows!
Sterta: rozmiar=%u, uæyte=%u, wolne=%u, max-dost©pne=%u bajt¢w\n
Uæycie flagi InDOS i RESET drive
Ostatni bà•d: %u -\s
uæytkownik odm¢wià dost©pu do zapisu
nie moæna byào rozszerzyÜ katalogu FAT
za maào pami©ci - zwi©ksz stert©
nie moæna byào automatycznie zaàadowaÜ tablicy Unicode
?USEWINTIME
Strefa czasowa to
%37s UTC%+d\n
?
?PROFILE
Profil.\n
Profil zresetowany.\n
%7lu %2d.%03d %s\n
Kalibracja profilu.\n
Staàa czasowa profilu = %lu000\n
Bà•d podczas kalibracji\n
?
