# language: Slovenian (SlovenÁüina, sl)
# codepage: CP852
# translators: Gemini
# To je samodejno ustvarjeno besedilo. ¨e najdete napake,
# jih popravite in o tem obvestite skupino FreeDOS.

naloßen, porablja %u bajtov.
naloßen v visoki pomnilnik, porablja %u bajtov.
\nNe najdem/ne morem odpreti datoteke s tabelo Unicode %s!
\nDatoteka %s: napaüna vsebina ali je ni mogoüe prebrati!
onemogoüen.
\n(Drug TSR je zasedel Int21 in/ali Int2F)
Êe ni nameÁüen!
zahteva vsaj DOS razliüico 4!
stikalo(a) upoÁtevano
"
++ FREEWARE ++
Program, ki podpira dolga imena datotek v üistem DOS-u.
UPORABA TEGA PROGRAMA JE NA LASTNO ODGOVORNOST, MO¶NA JE IZGUBA PODATKOV
Dejanja:     - (niü)	     naloßi in/ali omogoüi TSR
	     - h ali ?	     ta pomoü
	     - d	     onemogoüi DOSLFN
	     - s	     pokaßi stanje in nastavitve
?PROFILE
	     - p	     pokaßi podatke profila
	     - pr	     ponastavi podatke profila
	     - pc	     kalibriraj üas profila
?
	     - u	     odstrani TSR
Stikala:     - w{+|-}	     * dostop za pisanje
	     - ~{+|-}	     * uporaba tilde (NameNumericTail)
	     - t{+|-}	     * ohrani dolga imena (uüinek tunela)
	     - f{+|-}	     * zasilni naüin: LFN za vse pogone
	     - c{+|-}	     * podpora za CD-ROM
	     - i{+|-}	     * zaklep ponovnega vstopa (InDOS/RESET)
	     - r{+|-}	     * bit "samo za branje" za CD datoteke
?USEWINTIME
	     - o[N]	     * nastavi üasovni pas N ali preberi TZ
?
	     - z[:|=]tabela  naloßi tabelo Unicode (.TBL)
	     - m[:|=]bajti   deklariraj velikost kupa, 600..50000
	     - ms[:|=]bajti  deklariraj vel. kratke poti, 16..141
	     - ml[:|=]bajti  deklariraj vel. dolge poti, 16..1024
	     - mn[:|=]bajti  deklariraj vel. dolgega imena, 13..512
	     - p[:|=]pot     deklariraj delovno mapo za .TBL/.386
Okolje:      LANG=cc	     jezik za sporoüila (NLS\DOSLFN.cc)
?USEWINTIME
	     TZ=xxxNyyy      üasovni pas N, brez poletnega üasa
?
Email:	  %s
Download: %s
	  %s
"
aktiven
omogoüen.
odstranjen iz pomnilnika.
%7lu dostopov za branje
%7lu dostopov za pisanje
%7lu klicev Int21/AH=71
dostop za pisanje
uporaba tilde
uüinek tunela
podpora za CD-ROM
zasilni naüin
bit "samo za branje" na CD datotekah
neveljavna velikost kupa
ON
OFF
%41s %s\n
mapa ne obstaja!
ne morem nastaviti delovne mape
ne morem spremeniti velikosti kupa
stikalo zavrnjeno
 - najprej odstranite TSR.
\nTa program je neuporaben v DOS oknu te razliüice Windows!
Kup: velikost=%u, porabljeno=%u, prosto=%u, maks-na-voljo=%u bajtov\n
Uporaba zastavice InDOS in RESET drive
Zadnja napaka: %u -\s
uporabnik je zavrnil dostop za pisanje
ni bilo mogoüe razÁiriti mape FAT
ni dovolj pomnilnika - poveüajte kup
samodejno nalaganje tabele Unicode ni uspelo
?USEWINTIME
¨asovni pas je
%41s UTC%+d\n
?
?PROFILE
Profil.\n
Profil ponastavljen.\n
%7lu %2d.%03d %s\n
Kalibriranje profila.\n
Konstanta üasov profila = %lu000\n
Napaka med kalibracijo\n
?
