# Slovak, sk, cp 852
# Translation made by Google Gemini
# This translation was made by Google AI, please help the FreeDOS group
# to improve it.

naü°tanÇ, spotreba %u bajtov.
naü°tanÇ v hornej pamÑti, spotreba %u bajtov.
\nNemoßno n†jsú/otvoriú s£bor Unicode tabuñky %s!
\nNespr†vny obsah s£boru %s alebo chyba pri ü°tan°!
vypnutÇ.
\n(InÏ TSR program obsadil Int21 a/alebo Int2F)
EÁte nie je nainÁtalovanÇ!
vyßaduje aspoÂ DOS verzie 4!
prep°naü(e) prijatÏ(Ç)
"
++ FREEWARE ++
Program podporuj£ci dlhÇ n†zvy s£borov v üistom DOS-e.
POU¶÷VAJTE TENTO PROGRAM NA VLASTNê RIZIKO, M‚¶E D‚JSõ K STRATE ÈDAJOV
Akcie: - (niü) naü°taú a/alebo povoliú TSR
- h alebo ? tento pomocn°k
- d vypn£ú DOSLFN
- s zobraziú stav a nastavenia
?PROFILE
- p zobraziú profilovÇ £daje
- pr vynulovaú profilovÇ £daje
- pc kalibrovaú üasovanie profilu
?
- u odstr†niú TSR z pamÑte
Prep°naüe: - w{+|-} * pr°stup k z†pisu
- ~{+|-} * poußitie tildy (skr†tenÇ n†zvy)
- t{+|-} * tunelovÏ efekt (zachovanie n†zvov)
- f{+|-} * n£dzovÏ reßim - LFN pre vÁetky disky
- c{+|-} * podpora CDROM
- i{+|-} * z†mok cez InDOS pr°znak + RESET DRIVE
- r{+|-} * atrib£t len na ü°tanie pre CD s£bory
?USEWINTIME
- o[N] * nastaviú üasovÇ p†smo N alebo naü°taú TZ
?
- z[:|=]tabuñka naü°taú Unicode tabuñku (.TBL)
- m[:|=]bajtov veñkosú internej pamÑte (heap), 600..50000
- ms[:|=]bajtov veñkosú kr†tkej cesty, 16..141
- ml[:|=]bajtov veñkosú dlhej cesty, 16..1024
- mn[:|=]bajtov veñkosú dlhÇho n†zvu, 13..512
- p[:|=]cesta pracovnÏ adres†r pre .TBL/.386
Prostredie: LANG=cc jazyk spr†v (NLS\DOSLFN.cc)
?USEWINTIME
TZ=xxxNyyy üasovÇ p†smo N pre prevod üasu, bez DST
?
Email: %s
Download: %s
%s
"
akt°vne
povolenÇ.
odstr†nenÇ z pamÑte.
%7lu pr°stupov pre ü°tanie
%7lu pr°stupov pre z†pis
%7lu volan° Int21/AH=71
pr°stup k z†pisu
poußitie tildy
tunelovÏ efekt
podpora CDROM
n£dzovÏ reßim
atrib£t len na ü°tanie na CD s£boroch
neplatn† veñkosú haldy (heap)
ZAP
VYP
%35s %s\n
adres†r neexistuje!
nemoßno nastaviú pracovnÏ adres†r
nemoßno zmeniú veñkosú haldy
prep°naü odmietnutÏ

    najprv odstr†Âte TSR z pamÑte.
    \nTento program je v DOS okne tejto verzie Windows zbytoünÏ!
    Heap: veñkosú=%u, vyußitÇ=%u, voñnÇ=%u, max-dostupnÇ=%u bajtov\n
    InDOS pr°znak a poußitie RESET drive
    Posledn† chyba: %u -\s
    pouß°vateñ zak†zal pr°stup k z†pisu
    nemoßno rozÁ°riú FAT adres†r
    nedostatok pamÑte - zvÑüÁite "heap"
    nemoßno automaticky naü°taú Unicode tabuñku
    ?USEWINTIME
    ¨asovÇ p†smo je
    %35s UTC%+d\n
    ?
    ?PROFILE
    Profil.\n
    Profil vynulovanÏ.\n
    %7lu %2d.%03d %s\n
    Kalibr†cia profilu.\n
    ¨asov† konÁtanta profilu = %lu000\n
    Chyba pri kalibr†cii\n
    ?
