# Language: Slovak
# File ending: SK
# Codepage: 852
# This translation was made by MS Copilot.
# Please help the FreeDOS group to improve it.

0.0:Pou§itie: MD5SUM [/TBV] [/C [s£bor]] | [s£bor...]
0.1:Generuje alebo kontroluje MD5 kontroln‚ s£Ÿty spr v
0.2:    /C           kontrolovaœ kontroln‚ s£Ÿty (predvolen‚ je generovaœ)
0.3:    /[-]V        zapn£œ alebo vypn£œ podrobnì re§im (predvolen‚ vypnut‚)
0.4:    /[-]L        zapn£œ alebo vypn£œ pou§itie LFN (predvolen‚ zapnut‚, ak podporovan‚)
0.5:    /[-]R[num]   zapn£œ alebo vypn£œ rekurziu (predvolen‚ vypnut‚)
0.6:                 num je Ÿ¡slo od 1 do 9 a obmedzuje rekurziu (predvolen‚=4)
0.7:    /[-]S        rovnak‚ ako /[-]R=]
0.8:    /T           Ÿ¡taœ s£bory v textovom re§ime
0.9:    /B           Ÿ¡taœ s£bory v bin rnom re§ime (predvolen‚; prep¡çe /T)
0.10:    /M[:|=]mode  vybraœ re§im kontroln‚ho s£Ÿtu (SHA alebo MD5)
0.11:Vstup pre /C mus¡ byœ zoznam kontrolnìch s£Ÿtov a n zvov s£borov,
0.12:ktorì tento program vyp¡çe na stdout pri generovan¡ s£Ÿtov.
0.13:Argument pre /M mus¡ byœ re§im kontroln‚ho s£Ÿtu, ktorì m“§e byœ SHA,
0.14:CRC32, SHA256 alebo MD5, pod–a toho, ako bol MD5SUM skompilovanì.

1.0:Neplatn  vo–ba v
1.1:S£bor neexistuje
1.2:chyba Ÿ¡tania na stdin
1.3:chyba pri Ÿ¡tan¡
1.4:nerozpoznanì riadok
1.5:ned  sa otvoriœ
1.6:ZLYHALO
1.7:kontrola zlyhala pre
1.8:z
1.9:s£bor(y) nepreçli kontrolou
1.10:nebol skontrolovanì §iadny s£bor
1.11:S£bor je podadres r
1.12:Upozornenie: LFN nie s£ podporovan‚
1.13:Vo–be chìba argument
1.14:Neplatnì re§im kontroln‚ho s£Ÿtu
1.15:Adres r neexistuje
1.16:Nepodarilo sa z¡skaœ aktu lny adres r

