# Language: Slovak
# File ending: SK
# Codepage: 852
# This translation was made by Google Gemini.
# Please help the FreeDOS group to improve it.

pou§itie: BLKDROP.EXE [vo–by]

    [vo–by]      Iste, akoby si naozaj nejak£ vo–bu potreboval

BlockDrop vy§aduje myç a poŸ¡taŸ 386 alebo lepç¡ s grafikou VGA. K pridaniu
zvuku som sa eçte nedostal. Niekedy v bud£cnosti.

Z kladn  myçlienka hry nie je pr¡liç zlo§it . V z vislosti od £rovne je do
pr¡sunu blokov n hodne umiestnenì poŸet farebnìch a çpeci lnych blokov.

N h–ad pr¡sunu je v pravom dolnom rohu obrazovky. Ukazuje a§ Ôalç¡ch 20 riadkov
blokov. KeÔ blok dosiahne spodn£ Ÿasœ pr¡sunu, zobraz¡ sa vo v„Ÿçom detaile
nad z¢nou dopadu.

Na rozdiel od niektorìch inìch hier padaj£ bloky nad z¢nou dopadu priamo nadol a
nemo§no nimi hìbaœ. Nakoniec pristan£ na kope. Kìm nepristan£, s£ im£nne voŸi
akejko–vek interakcii.

Nenechajte bloky naskladaœ pr¡liç vysoko. Zablokuj£ pr¡sun a vy strat¡te §ivot,
Ÿo v s prin£ti zaŸaœ £roveå odznova.

Ale nebojte sa, keÔ s£ u§ bloky na kope, existuje viacero sp“sobov, ako ich
odstr niœ a kopu skr tiœ. Vo vçeobecnosti mo§no klikn£œ na skupinu troch alebo
viacerìch blokov, aby sa odstr nili. ¬¡m viac blokov v danej skupine, tìm viac
bodov.

Existuj£ tvrd‚ bloky (vyzeraj£ trochu ako Ÿerven‚ X), na ktor‚ nemo§no klikn£œ
pre odstr nenie bez oh–adu na to, ko–ko sa ich vz jomne dotìka. M“§ete sa ich
zbaviœ iba odp len¡m çtandardnej bomby v bl¡zkosti. Tìm sa odstr nia vçetky
bloky v bezprostrednej bl¡zkosti bomby.

Existuj£ tie§ çpeci lne bloky s farebnìmi bombami, ktor‚ z kopy odstr nia
vçetky bloky rovnakej farby. A Ôalçie typy blokov pre çpeci lne £lohy.

KeÔ sa bloky z kopy odstr nia, padaj£ce bloky £myselne trochu v haj£, aby sa
kopa mohla plne sesun£œ predtìm, ne§ pristan£.

Aha... Ak dosiahnete dostatoŸne vysok£ £roveå a n hodou niekedy uvid¡te lebku
so skr¡§enìmi hn tmi, neklikajte na åu. Znamen  to okam§it£ smrœ. Je to jedinì
blok, na ktorì nikdy nechcete klikn£œ.

PoŸas hrania m“§ete pomocou -/+ obŸas hru spomaliœ alebo zrìchliœ. Nem  to
§iadny vplyv na vaçe sk¢re a je to urŸen‚ pre sk£senìch hr Ÿov, ktor¡ by sa
v ni§ç¡ch pomalç¡ch £rovniach mohli nudiœ.

Na zaŸiatku £rovne m“§ete stlaŸen¡m tabul tora t£to £roveå preskoŸiœ. Ale pozor,
£rovne s£ len rìchlejçie a n roŸnejçie.

V s£Ÿasnosti, keÔ s£ bloky odstr nen‚ z kopy, ses£vaj£ sa len smerom nadol.
Zva§ujem vçak, §e by sa hìbali aj dovn£tra, aby vyplnili pr zdne st’pce. Tie§
si mysl¡m, §e hra m“§e byœ pr¡liç rìchlo pr¡liç n roŸn . Mo§no bud£ na mieste
nejak‚ £pravy tempa n roŸnosti. Potom by sa namiesto neust leho zrìch–ovania
mohol zvyçovaœ poŸet s£Ÿasne padaj£cich blokov. Ale nateraz len poŸk m a
uvid¡m, Ÿo si pou§¡vatelia o hre doteraz myslia.

Som si istì, §e na zvyçok pr¡dete sami.

:-)

